from urllib.parse import urlencode
from lxml import html

import urllib.request as urllib2
import re 


DEFAULT_ENCODING = "utf8"
DEFAULT_TIMEOUT = 240

ROOT_URL = "http://www.whatsthescore.com"
SEARCH_URL = ROOT_URL+"/search/?"

URL_PARAMS = {
	"filter[]":"event",
	"sport[]":"1",
	"q":"Algeria vs Bosnia and Herzegovina 14 November 2012"
}



def request(url):
	"""Makes an HTTP GET request to the specified URL.
	
	Keyword arguments:
    url -- url for the request
	"""
	try:
		raw_response = urllib2.urlopen(url=url, timeout = DEFAULT_TIMEOUT)
		charset = raw_response.info().get_param('charset', DEFAULT_ENCODING)
	except urllib2.HTTPError as err:
		print("ERROR {0} for {1}".format(err.code,url))
		raw_response = None
	
		
	return raw_response.read().decode(charset) if raw_response else ''



match_data =[
	{ "teamA":"Algeria","teamB":"Armenia","matchDate":"31 May 2014","query":"Algeria vs Armenia 31 May 2014" } ,
	{ "teamA":"Algeria","teamB":"Bosnia and Herzegovina","matchDate":"14 November 2012","query":"Algeria vs Bosnia and Herzegovina 14 November 2012" } ,
	{ "teamA":"Algeria","teamB":"Ivory Coast","matchDate":"30 January 2013","query":"Algeria vs Ivory Coast 30 January 2013" } ,
	{ "teamA":"Algeria","teamB":"Morocco","matchDate":"27 March 2011","query":"Algeria vs Morocco 27 March 2011" } ,
	{ "teamA":"Morocco","teamB":"Algeria","matchDate":"04 June 2011","query":"Morocco vs Algeria 04 June 2011" } ,
	{ "teamA":"Oman","teamB":"Algeria","matchDate":"29 August 1998","query":"Oman vs Algeria 29 August 1998" } ,
	{ "teamA":"Oman","teamB":"Algeria","matchDate":"31 August 1998","query":"Oman vs Algeria 31 August 1998" } ,
	{ "teamA":"Oman","teamB":"Algeria","matchDate":"30 March 2015","query":"Oman vs Algeria 30 March 2015" } ,
	{ "teamA":"South Africa","teamB":"Algeria","matchDate":"12 January 2013","query":"South Africa vs Algeria 12 January 2013" } ,
	{ "teamA":"Algeria","teamB":"Tunisia","matchDate":"11 December 1987","query":"Algeria vs Tunisia 11 December 1987" } ,
	{ "teamA":"Algeria","teamB":"Tunisia","matchDate":"12 November 2011","query":"Algeria vs Tunisia 12 November 2011" } ,
	{ "teamA":"Algeria","teamB":"United Arab Emirates","matchDate":"05 June 2010","query":"Algeria vs United Arab Emirates 05 June 2010" } ,
	{ "teamA":"Argentina","teamB":"Bolivia","matchDate":"06 June 2015","query":"Argentina vs Bolivia 06 June 2015" } ,
	{ "teamA":"Argentina","teamB":"Mexico","matchDate":"08 September 2015","query":"Argentina vs Mexico 08 September 2015" } ,
	{ "teamA":"Bulgaria","teamB":"Armenia","matchDate":"11 September 2012","query":"Bulgaria vs Armenia 11 September 2012" } ,
	{ "teamA":"Armenia","teamB":"Canada","matchDate":"29 February 2012","query":"Armenia vs Canada 29 February 2012" } ,
	{ "teamA":"Denmark","teamB":"Armenia","matchDate":"11 June 2013","query":"Denmark vs Armenia 11 June 2013" } ,
	{ "teamA":"El Salvador","teamB":"Armenia","matchDate":"01 June 2016","query":"El Salvador vs Armenia 01 June 2016" } ,
	{ "teamA":"Armenia","teamB":"Greece","matchDate":"06 September 2003","query":"Armenia vs Greece 06 September 2003" } ,
	{ "teamA":"Guatemala","teamB":"Armenia","matchDate":"28 May 2016","query":"Guatemala vs Armenia 28 May 2016" } ,
	{ "teamA":"Armenia","teamB":"Iran","matchDate":"11 August 2010","query":"Armenia vs Iran 11 August 2010" } ,
	{ "teamA":"Lithuania","teamB":"Armenia","matchDate":"10 August 2011","query":"Lithuania vs Armenia 10 August 2011" } ,
	{ "teamA":"Armenia","teamB":"Lithuania","matchDate":"14 November 2012","query":"Armenia vs Lithuania 14 November 2012" } ,
	{ "teamA":"United Arab Emirates","teamB":"Armenia","matchDate":"27 May 2014","query":"United Arab Emirates vs Armenia 27 May 2014" } ,
	{ "teamA":"Armenia","teamB":"Uzbekistan","matchDate":"25 May 2010","query":"Armenia vs Uzbekistan 25 May 2010" } ,
	{ "teamA":"China PR","teamB":"Australia","matchDate":"22 January 2015","query":"China PR vs Australia 22 January 2015" } ,
	{ "teamA":"Germany","teamB":"Australia","matchDate":"25 March 2015","query":"Germany vs Australia 25 March 2015" } ,
	{ "teamA":"Australia","teamB":"United Arab Emirates","matchDate":"27 January 2015","query":"Australia vs United Arab Emirates 27 January 2015" } ,
	{ "teamA":"Serbia","teamB":"Austria","matchDate":"06 June 2009","query":"Serbia vs Austria 06 June 2009" } ,
	{ "teamA":"China PR","teamB":"Bahrain","matchDate":"11 August 2010","query":"China PR vs Bahrain 11 August 2010" } ,
	{ "teamA":"Bahrain","teamB":"Colombia","matchDate":"26 March 2015","query":"Bahrain vs Colombia 26 March 2015" } ,
	{ "teamA":"Bahrain","teamB":"Denmark","matchDate":"30 January 2008","query":"Bahrain vs Denmark 30 January 2008" } ,
	{ "teamA":"Hong Kong","teamB":"Bahrain","matchDate":"21 January 2009","query":"Hong Kong vs Bahrain 21 January 2009" } ,
	{ "teamA":"Bahrain","teamB":"Hong Kong","matchDate":"06 January 2010","query":"Bahrain vs Hong Kong 06 January 2010" } ,
	{ "teamA":"Bahrain","teamB":"Iran","matchDate":"21 March 2008","query":"Bahrain vs Iran 21 March 2008" } ,
	{ "teamA":"Bahrain","teamB":"Iran","matchDate":"31 August 2009","query":"Bahrain vs Iran 31 August 2009" } ,
	{ "teamA":"Iran","teamB":"Bahrain","matchDate":"24 September 2010","query":"Iran vs Bahrain 24 September 2010" } ,
	{ "teamA":"Iran","teamB":"Bahrain","matchDate":"11 October 2011","query":"Iran vs Bahrain 11 October 2011" } ,
	{ "teamA":"Bahrain","teamB":"Iran","matchDate":"11 November 2011","query":"Bahrain vs Iran 11 November 2011" } ,
	{ "teamA":"Bahrain","teamB":"Iraq","matchDate":"21 January 2007","query":"Bahrain vs Iraq 21 January 2007" } ,
	{ "teamA":"Bahrain","teamB":"Iraq","matchDate":"04 January 2009","query":"Bahrain vs Iraq 04 January 2009" } ,
	{ "teamA":"Bahrain","teamB":"Iraq","matchDate":"26 November 2010","query":"Bahrain vs Iraq 26 November 2010" } ,
	{ "teamA":"Bahrain","teamB":"Iraq","matchDate":"13 December 2011","query":"Bahrain vs Iraq 13 December 2011" } ,
	{ "teamA":"Bahrain","teamB":"Iraq","matchDate":"03 December 2012","query":"Bahrain vs Iraq 03 December 2012" } ,
	{ "teamA":"Bahrain","teamB":"Iraq","matchDate":"15 January 2013","query":"Bahrain vs Iraq 15 January 2013" } ,
	{ "teamA":"Bahrain","teamB":"Japan","matchDate":"06 September 2008","query":"Bahrain vs Japan 06 September 2008" } ,
	{ "teamA":"Bahrain","teamB":"Korea DPR","matchDate":"04 January 2011","query":"Bahrain vs Korea DPR 04 January 2011" } ,
	{ "teamA":"Bahrain","teamB":"Korea Republic","matchDate":"04 February 2009","query":"Bahrain vs Korea Republic 04 February 2009" } ,
	{ "teamA":"Korea Republic","teamB":"Bahrain","matchDate":"10 January 2011","query":"Korea Republic vs Bahrain 10 January 2011" } ,
	{ "teamA":"Morocco","teamB":"Bahrain","matchDate":"23 June 2012","query":"Morocco vs Bahrain 23 June 2012" } ,
	{ "teamA":"Bahrain","teamB":"Oman","matchDate":"16 April 2001","query":"Bahrain vs Oman 16 April 2001" } ,
	{ "teamA":"Oman","teamB":"Bahrain","matchDate":"10 September 2003","query":"Oman vs Bahrain 10 September 2003" } ,
	{ "teamA":"Oman","teamB":"Bahrain","matchDate":"08 November 2006","query":"Oman vs Bahrain 08 November 2006" } ,
	{ "teamA":"Oman","teamB":"Bahrain","matchDate":"27 January 2007","query":"Oman vs Bahrain 27 January 2007" } ,
	{ "teamA":"Oman","teamB":"Bahrain","matchDate":"10 January 2009","query":"Oman vs Bahrain 10 January 2009" } ,
	{ "teamA":"Bahrain","teamB":"Oman","matchDate":"26 September 2010","query":"Bahrain vs Oman 26 September 2010" } ,
	{ "teamA":"Oman","teamB":"Bahrain","matchDate":"23 November 2010","query":"Oman vs Bahrain 23 November 2010" } ,
	{ "teamA":"Oman","teamB":"Bahrain","matchDate":"10 August 2011","query":"Oman vs Bahrain 10 August 2011" } ,
	{ "teamA":"Oman","teamB":"Bahrain","matchDate":"20 December 2012","query":"Oman vs Bahrain 20 December 2012" } ,
	{ "teamA":"Bahrain","teamB":"Oman","matchDate":"05 January 2013","query":"Bahrain vs Oman 05 January 2013" } ,
	{ "teamA":"Oman","teamB":"Bahrain","matchDate":"25 December 2013","query":"Oman vs Bahrain 25 December 2013" } ,
	{ "teamA":"Bahrain","teamB":"Palestine","matchDate":"02 September 2004","query":"Bahrain vs Palestine 02 September 2004" } ,
	{ "teamA":"Bahrain","teamB":"Palestine","matchDate":"16 February 2006","query":"Bahrain vs Palestine 16 February 2006" } ,
	{ "teamA":"Bahrain","teamB":"Palestine","matchDate":"06 December 2011","query":"Bahrain vs Palestine 06 December 2011" } ,
	{ "teamA":"Bahrain","teamB":"Palestine","matchDate":"20 December 2011","query":"Bahrain vs Palestine 20 December 2011" } ,
	{ "teamA":"Palestine","teamB":"Bahrain","matchDate":"29 November 2012","query":"Palestine vs Bahrain 29 November 2012" } ,
	{ "teamA":"Bahrain","teamB":"Panama","matchDate":"27 October 2005","query":"Bahrain vs Panama 27 October 2005" } ,
	{ "teamA":"Saudi Arabia","teamB":"Bahrain","matchDate":"09 August 2006","query":"Saudi Arabia vs Bahrain 09 August 2006" } ,
	{ "teamA":"Saudi Arabia","teamB":"Bahrain","matchDate":"18 January 2007","query":"Saudi Arabia vs Bahrain 18 January 2007" } ,
	{ "teamA":"Saudi Arabia","teamB":"Bahrain","matchDate":"12 November 2008","query":"Saudi Arabia vs Bahrain 12 November 2008" } ,
	{ "teamA":"Bahrain","teamB":"Saudi Arabia","matchDate":"23 December 2008","query":"Bahrain vs Saudi Arabia 23 December 2008" } ,
	{ "teamA":"Bahrain","teamB":"Saudi Arabia","matchDate":"31 December 2010","query":"Bahrain vs Saudi Arabia 31 December 2010" } ,
	{ "teamA":"Bahrain","teamB":"Saudi Arabia","matchDate":"15 December 2012","query":"Bahrain vs Saudi Arabia 15 December 2012" } ,
	{ "teamA":"Bahrain","teamB":"Saudi Arabia","matchDate":"30 December 2014","query":"Bahrain vs Saudi Arabia 30 December 2014" } ,
	{ "teamA":"Bahrain","teamB":"Sweden","matchDate":"18 January 2012","query":"Bahrain vs Sweden 18 January 2012" } ,
	{ "teamA":"United Arab Emirates","teamB":"Bahrain","matchDate":"31 July 1992","query":"United Arab Emirates vs Bahrain 31 July 1992" } ,
	{ "teamA":"United Arab Emirates","teamB":"Bahrain","matchDate":"31 May 2004","query":"United Arab Emirates vs Bahrain 31 May 2004" } ,
	{ "teamA":"United Arab Emirates","teamB":"Bahrain","matchDate":"27 June 2007","query":"United Arab Emirates vs Bahrain 27 June 2007" } ,
	{ "teamA":"United Arab Emirates","teamB":"Bahrain","matchDate":"29 August 2008","query":"United Arab Emirates vs Bahrain 29 August 2008" } ,
	{ "teamA":"United Arab Emirates","teamB":"Bahrain","matchDate":"29 November 2010","query":"United Arab Emirates vs Bahrain 29 November 2010" } ,
	{ "teamA":"United Arab Emirates","teamB":"Bahrain","matchDate":"16 October 2012","query":"United Arab Emirates vs Bahrain 16 October 2012" } ,
	{ "teamA":"Bahrain","teamB":"United Arab Emirates","matchDate":"08 January 2013","query":"Bahrain vs United Arab Emirates 08 January 2013" } ,
	{ "teamA":"Bahrain","teamB":"Uzbekistan","matchDate":"17 June 2009","query":"Bahrain vs Uzbekistan 17 June 2009" } ,
	{ "teamA":"Bahrain","teamB":"Uzbekistan","matchDate":"12 October 2010","query":"Bahrain vs Uzbekistan 12 October 2010" } ,
	{ "teamA":"Bahrain","teamB":"Uzbekistan","matchDate":"25 December 2010","query":"Bahrain vs Uzbekistan 25 December 2010" } ,
	{ "teamA":"Colombia","teamB":"Bolivia","matchDate":"10 July 2011","query":"Colombia vs Bolivia 10 July 2011" } ,
	{ "teamA":"Bolivia","teamB":"Colombia","matchDate":"11 October 2011","query":"Bolivia vs Colombia 11 October 2011" } ,
	{ "teamA":"Bolivia","teamB":"Costa Rica","matchDate":"07 July 2011","query":"Bolivia vs Costa Rica 07 July 2011" } ,
	{ "teamA":"Bolivia","teamB":"Costa Rica","matchDate":"14 November 2012","query":"Bolivia vs Costa Rica 14 November 2012" } ,
	{ "teamA":"Bolivia","teamB":"Cuba","matchDate":"29 February 2012","query":"Bolivia vs Cuba 29 February 2012" } ,
	{ "teamA":"Ecuador","teamB":"Bolivia","matchDate":"07 September 2012","query":"Ecuador vs Bolivia 07 September 2012" } ,
	{ "teamA":"Bolivia","teamB":"Ecuador","matchDate":"05 September 2014","query":"Bolivia vs Ecuador 05 September 2014" } ,
	{ "teamA":"Greece","teamB":"Bolivia","matchDate":"06 June 2014","query":"Greece vs Bolivia 06 June 2014" } ,
	{ "teamA":"Greece","teamB":"Bolivia","matchDate":"07 June 2014","query":"Greece vs Bolivia 07 June 2014" } ,
	{ "teamA":"Guatemala","teamB":"Bolivia","matchDate":"28 March 2011","query":"Guatemala vs Bolivia 28 March 2011" } ,
	{ "teamA":"Japan","teamB":"Bolivia","matchDate":"19 June 2000","query":"Japan vs Bolivia 19 June 2000" } ,
	{ "teamA":"Mexico","teamB":"Bolivia","matchDate":"11 March 2009","query":"Mexico vs Bolivia 11 March 2009" } ,
	{ "teamA":"Panama","teamB":"Bolivia","matchDate":"25 March 2011","query":"Panama vs Bolivia 25 March 2011" } ,
	{ "teamA":"Bolivia","teamB":"Panama","matchDate":"10 August 2011","query":"Bolivia vs Panama 10 August 2011" } ,
	{ "teamA":"Bolivia","teamB":"Paraguay","matchDate":"04 June 2011","query":"Bolivia vs Paraguay 04 June 2011" } ,
	{ "teamA":"Paraguay","teamB":"Bolivia","matchDate":"07 June 2011","query":"Paraguay vs Bolivia 07 June 2011" } ,
	{ "teamA":"Peru","teamB":"Bolivia","matchDate":"02 September 2011","query":"Peru vs Bolivia 02 September 2011" } ,
	{ "teamA":"Bolivia","teamB":"Peru","matchDate":"05 September 2011","query":"Bolivia vs Peru 05 September 2011" } ,
	{ "teamA":"Bolivia","teamB":"Peru","matchDate":"12 October 2012","query":"Bolivia vs Peru 12 October 2012" } ,
	{ "teamA":"Bolivia","teamB":"Uruguay","matchDate":"16 October 2012","query":"Bolivia vs Uruguay 16 October 2012" } ,
	{ "teamA":"Bolivia","teamB":"Venezuela","matchDate":"06 June 2009","query":"Bolivia vs Venezuela 06 June 2009" } ,
	{ "teamA":"Bolivia","teamB":"Venezuela","matchDate":"07 October 2010","query":"Bolivia vs Venezuela 07 October 2010" } ,
	{ "teamA":"Bolivia","teamB":"Venezuela","matchDate":"07 June 2013","query":"Bolivia vs Venezuela 07 June 2013" } ,
	{ "teamA":"Venezuela","teamB":"Bolivia","matchDate":"14 August 2013","query":"Venezuela vs Bolivia 14 August 2013" } ,
	{ "teamA":"Brazil","teamB":"Egypt","matchDate":"15 June 2009","query":"Brazil vs Egypt 15 June 2009" } ,
	{ "teamA":"Brazil","teamB":"Egypt","matchDate":"14 November 2011","query":"Brazil vs Egypt 14 November 2011" } ,
	{ "teamA":"Mexico","teamB":"Brazil","matchDate":"11 October 2011","query":"Mexico vs Brazil 11 October 2011" } ,
	{ "teamA":"Brazil","teamB":"Mexico","matchDate":"03 June 2012","query":"Brazil vs Mexico 03 June 2012" } ,
	{ "teamA":"Panama","teamB":"Brazil","matchDate":"30 May 2016","query":"Panama vs Brazil 30 May 2016" } ,
	{ "teamA":"Brazil","teamB":"Portugal","matchDate":"19 November 2008","query":"Brazil vs Portugal 19 November 2008" } ,
	{ "teamA":"Bulgaria","teamB":"Canada","matchDate":"23 May 2014","query":"Bulgaria vs Canada 23 May 2014" } ,
	{ "teamA":"Bulgaria","teamB":"Denmark","matchDate":"12 October 2012","query":"Bulgaria vs Denmark 12 October 2012" } ,
	{ "teamA":"Denmark","teamB":"Bulgaria","matchDate":"26 March 2013","query":"Denmark vs Bulgaria 26 March 2013" } ,
	{ "teamA":"Denmark","teamB":"Bulgaria","matchDate":"07 June 2016","query":"Denmark vs Bulgaria 07 June 2016" } ,
	{ "teamA":"Bulgaria","teamB":"Germany","matchDate":"21 August 2002","query":"Bulgaria vs Germany 21 August 2002" } ,
	{ "teamA":"Bulgaria","teamB":"Greece","matchDate":"30 June 1929","query":"Bulgaria vs Greece 30 June 1929" } ,
	{ "teamA":"Mexico","teamB":"Bulgaria","matchDate":"16 November 2005","query":"Mexico vs Bulgaria 16 November 2005" } ,
	{ "teamA":"Bulgaria","teamB":"Romania","matchDate":"15 September 1929","query":"Bulgaria vs Romania 15 September 1929" } ,
	{ "teamA":"Saudi Arabia","teamB":"Bulgaria","matchDate":"12 October 2010","query":"Saudi Arabia vs Bulgaria 12 October 2010" } ,
	{ "teamA":"Serbia","teamB":"Bulgaria","matchDate":"19 November 2008","query":"Serbia vs Bulgaria 19 November 2008" } ,
	{ "teamA":"Bulgaria","teamB":"Serbia","matchDate":"17 November 2010","query":"Bulgaria vs Serbia 17 November 2010" } ,
	{ "teamA":"Bulgaria","teamB":"Yugoslavia","matchDate":"15 June 1930","query":"Bulgaria vs Yugoslavia 15 June 1930" } ,
	{ "teamA":"Colombia","teamB":"Cameroon","matchDate":"16 October 2012","query":"Colombia vs Cameroon 16 October 2012" } ,
	{ "teamA":"Egypt","teamB":"Cameroon","matchDate":"20 May 2012","query":"Egypt vs Cameroon 20 May 2012" } ,
	{ "teamA":"Cameroon","teamB":"Ivory Coast","matchDate":"04 February 2006","query":"Cameroon vs Ivory Coast 04 February 2006" } ,
	{ "teamA":"Japan","teamB":"Cameroon","matchDate":"28 March 2001","query":"Japan vs Cameroon 28 March 2001" } ,
	{ "teamA":"Morocco","teamB":"Cameroon","matchDate":"15 November 2005","query":"Morocco vs Cameroon 15 November 2005" } ,
	{ "teamA":"Morocco","teamB":"Cameroon","matchDate":"13 November 2011","query":"Morocco vs Cameroon 13 November 2011" } ,
	{ "teamA":"South Africa","teamB":"Cameroon","matchDate":"19 November 2008","query":"South Africa vs Cameroon 19 November 2008" } ,
	{ "teamA":"Cameroon","teamB":"South Africa","matchDate":"26 March 2016","query":"Cameroon vs South Africa 26 March 2016" } ,
	{ "teamA":"Tunisia","teamB":"Cameroon","matchDate":"13 October 2013","query":"Tunisia vs Cameroon 13 October 2013" } ,
	{ "teamA":"Zambia","teamB":"Cameroon","matchDate":"01 June 1997","query":"Zambia vs Cameroon 01 June 1997" } ,
	{ "teamA":"Canada","teamB":"China PR","matchDate":"02 April 1992","query":"Canada vs China PR 02 April 1992" } ,
	{ "teamA":"Costa Rica","teamB":"Canada","matchDate":"10 July 2009","query":"Costa Rica vs Canada 10 July 2009" } ,
	{ "teamA":"Canada","teamB":"Costa Rica","matchDate":"28 May 2013","query":"Canada vs Costa Rica 28 May 2013" } ,
	{ "teamA":"Cuba","teamB":"Canada","matchDate":"08 June 2012","query":"Cuba vs Canada 08 June 2012" } ,
	{ "teamA":"Canada","teamB":"Cuba","matchDate":"12 October 2012","query":"Canada vs Cuba 12 October 2012" } ,
	{ "teamA":"Canada","teamB":"Denmark","matchDate":"26 January 2013","query":"Canada vs Denmark 26 January 2013" } ,
	{ "teamA":"Canada","teamB":"Ecuador","matchDate":"11 May 2010","query":"Canada vs Ecuador 11 May 2010" } ,
	{ "teamA":"Canada","teamB":"Ecuador","matchDate":"01 June 2011","query":"Canada vs Ecuador 01 June 2011" } ,
	{ "teamA":"El Salvador","teamB":"Canada","matchDate":"07 July 2009","query":"El Salvador vs Canada 07 July 2009" } ,
	{ "teamA":"Estonia","teamB":"Canada","matchDate":"26 March 2008","query":"Estonia vs Canada 26 March 2008" } ,
	{ "teamA":"Guatemala","teamB":"Canada","matchDate":"30 June 2009","query":"Guatemala vs Canada 30 June 2009" } ,
	{ "teamA":"Canada","teamB":"Honduras","matchDate":"06 September 2008","query":"Canada vs Honduras 06 September 2008" } ,
	{ "teamA":"Canada","teamB":"Honduras","matchDate":"18 July 2009","query":"Canada vs Honduras 18 July 2009" } ,
	{ "teamA":"Canada","teamB":"Honduras","matchDate":"07 September 2010","query":"Canada vs Honduras 07 September 2010" } ,
	{ "teamA":"Canada","teamB":"Honduras","matchDate":"12 June 2012","query":"Canada vs Honduras 12 June 2012" } ,
	{ "teamA":"Honduras","teamB":"Canada","matchDate":"16 October 2012","query":"Honduras vs Canada 16 October 2012" } ,
	{ "teamA":"Canada","teamB":"Jamaica","matchDate":"03 July 2009","query":"Canada vs Jamaica 03 July 2009" } ,
	{ "teamA":"Jamaica","teamB":"Canada","matchDate":"31 January 2010","query":"Jamaica vs Canada 31 January 2010" } ,
	{ "teamA":"Japan","teamB":"Canada","matchDate":"22 March 2013","query":"Japan vs Canada 22 March 2013" } ,
	{ "teamA":"Morocco","teamB":"Canada","matchDate":"11 October 2016","query":"Morocco vs Canada 11 October 2016" } ,
	{ "teamA":"Panama","teamB":"Canada","matchDate":"04 June 2008","query":"Panama vs Canada 04 June 2008" } ,
	{ "teamA":"Canada","teamB":"Panama","matchDate":"14 June 2011","query":"Canada vs Panama 14 June 2011" } ,
	{ "teamA":"Canada","teamB":"Panama","matchDate":"07 September 2012","query":"Canada vs Panama 07 September 2012" } ,
	{ "teamA":"Panama","teamB":"Canada","matchDate":"11 September 2012","query":"Panama vs Canada 11 September 2012" } ,
	{ "teamA":"Panama","teamB":"Canada","matchDate":"14 July 2013","query":"Panama vs Canada 14 July 2013" } ,
	{ "teamA":"Canada","teamB":"Peru","matchDate":"04 September 2010","query":"Canada vs Peru 04 September 2010" } ,
	{ "teamA":"Canada","teamB":"Trinidad and Tobago","matchDate":"15 August 2012","query":"Canada vs Trinidad and Tobago 15 August 2012" } ,
	{ "teamA":"Canada","teamB":"Uzbekistan","matchDate":"07 June 2016","query":"Canada vs Uzbekistan 07 June 2016" } ,
	{ "teamA":"Venezuela","teamB":"Canada","matchDate":"29 May 2010","query":"Venezuela vs Canada 29 May 2010" } ,
	{ "teamA":"Colombia","teamB":"Costa Rica","matchDate":"02 July 2011","query":"Colombia vs Costa Rica 02 July 2011" } ,
	{ "teamA":"Ecuador","teamB":"Colombia","matchDate":"10 June 2012","query":"Ecuador vs Colombia 10 June 2012" } ,
	{ "teamA":"Colombia","teamB":"Ecuador","matchDate":"06 September 2013","query":"Colombia vs Ecuador 06 September 2013" } ,
	{ "teamA":"Colombia","teamB":"El Salvador","matchDate":"07 August 2009","query":"Colombia vs El Salvador 07 August 2009" } ,
	{ "teamA":"Guatemala","teamB":"Colombia","matchDate":"06 February 2013","query":"Guatemala vs Colombia 06 February 2013" } ,
	{ "teamA":"Colombia","teamB":"Haiti","matchDate":"11 February 2009","query":"Colombia vs Haiti 11 February 2009" } ,
	{ "teamA":"Honduras","teamB":"Colombia","matchDate":"01 December 1996","query":"Honduras vs Colombia 01 December 1996" } ,
	{ "teamA":"Colombia","teamB":"Honduras","matchDate":"26 March 2008","query":"Colombia vs Honduras 26 March 2008" } ,
	{ "teamA":"Honduras","teamB":"Colombia","matchDate":"03 September 2011","query":"Honduras vs Colombia 03 September 2011" } ,
	{ "teamA":"Jamaica","teamB":"Colombia","matchDate":"06 September 2011","query":"Jamaica vs Colombia 06 September 2011" } ,
	{ "teamA":"Mexico","teamB":"Colombia","matchDate":"30 September 2009","query":"Mexico vs Colombia 30 September 2009" } ,
	{ "teamA":"Mexico","teamB":"Colombia","matchDate":"07 September 2010","query":"Mexico vs Colombia 07 September 2010" } ,
	{ "teamA":"Mexico","teamB":"Colombia","matchDate":"29 February 2012","query":"Mexico vs Colombia 29 February 2012" } ,
	{ "teamA":"Paraguay","teamB":"Colombia","matchDate":"15 October 2013","query":"Paraguay vs Colombia 15 October 2013" } ,
	{ "teamA":"Colombia","teamB":"Peru","matchDate":"17 November 2010","query":"Colombia vs Peru 17 November 2010" } ,
	{ "teamA":"Peru","teamB":"Colombia","matchDate":"03 June 2012","query":"Peru vs Colombia 03 June 2012" } ,
	{ "teamA":"Colombia","teamB":"Tunisia","matchDate":"05 March 2014","query":"Colombia vs Tunisia 05 March 2014" } ,
	{ "teamA":"Uruguay","teamB":"Colombia","matchDate":"06 February 2008","query":"Uruguay vs Colombia 06 February 2008" } ,
	{ "teamA":"Colombia","teamB":"Venezuela","matchDate":"30 April 2008","query":"Colombia vs Venezuela 30 April 2008" } ,
	{ "teamA":"Colombia","teamB":"Venezuela","matchDate":"12 August 2009","query":"Colombia vs Venezuela 12 August 2009" } ,
	{ "teamA":"Venezuela","teamB":"Colombia","matchDate":"03 September 2010","query":"Venezuela vs Colombia 03 September 2010" } ,
	{ "teamA":"Colombia","teamB":"Venezuela","matchDate":"11 November 2011","query":"Colombia vs Venezuela 11 November 2011" } ,
	{ "teamA":"Venezuela","teamB":"Colombia","matchDate":"26 March 2013","query":"Venezuela vs Colombia 26 March 2013" } ,
	{ "teamA":"Costa Rica","teamB":"Cuba","matchDate":"05 June 2011","query":"Costa Rica vs Cuba 05 June 2011" } ,
	{ "teamA":"Cuba","teamB":"Costa Rica","matchDate":"11 December 2011","query":"Cuba vs Costa Rica 11 December 2011" } ,
	{ "teamA":"Cuba","teamB":"El Salvador","matchDate":"24 March 2011","query":"Cuba vs El Salvador 24 March 2011" } ,
	{ "teamA":"El Salvador","teamB":"Cuba","matchDate":"12 June 2011","query":"El Salvador vs Cuba 12 June 2011" } ,
	{ "teamA":"Guatemala","teamB":"Cuba","matchDate":"23 August 2014","query":"Guatemala vs Cuba 23 August 2014" } ,
	{ "teamA":"Haiti","teamB":"Cuba","matchDate":"17 October 2006","query":"Haiti vs Cuba 17 October 2006" } ,
	{ "teamA":"Haiti","teamB":"Cuba","matchDate":"19 October 2006","query":"Haiti vs Cuba 19 October 2006" } ,
	{ "teamA":"Haiti","teamB":"Cuba","matchDate":"08 November 2006","query":"Haiti vs Cuba 08 November 2006" } ,
	{ "teamA":"Cuba","teamB":"Haiti","matchDate":"08 December 2008","query":"Cuba vs Haiti 08 December 2008" } ,
	{ "teamA":"Haiti","teamB":"Cuba","matchDate":"14 December 2012","query":"Haiti vs Cuba 14 December 2012" } ,
	{ "teamA":"Cuba","teamB":"Honduras","matchDate":"07 September 2012","query":"Cuba vs Honduras 07 September 2012" } ,
	{ "teamA":"Honduras","teamB":"Cuba","matchDate":"11 September 2012","query":"Honduras vs Cuba 11 September 2012" } ,
	{ "teamA":"Jamaica","teamB":"Cuba","matchDate":"22 February 2012","query":"Jamaica vs Cuba 22 February 2012" } ,
	{ "teamA":"Jamaica","teamB":"Cuba","matchDate":"24 February 2012","query":"Jamaica vs Cuba 24 February 2012" } ,
	{ "teamA":"Jamaica","teamB":"Cuba","matchDate":"12 December 2012","query":"Jamaica vs Cuba 12 December 2012" } ,
	{ "teamA":"Mexico","teamB":"Cuba","matchDate":"27 November 1990","query":"Mexico vs Cuba 27 November 1990" } ,
	{ "teamA":"Cuba","teamB":"Mexico","matchDate":"09 June 2011","query":"Cuba vs Mexico 09 June 2011" } ,
	{ "teamA":"Panama","teamB":"Cuba","matchDate":"26 October 2010","query":"Panama vs Cuba 26 October 2010" } ,
	{ "teamA":"Cuba","teamB":"Panama","matchDate":"29 March 2011","query":"Cuba vs Panama 29 March 2011" } ,
	{ "teamA":"Panama","teamB":"Cuba","matchDate":"12 June 2012","query":"Panama vs Cuba 12 June 2012" } ,
	{ "teamA":"Cuba","teamB":"Panama","matchDate":"16 October 2012","query":"Cuba vs Panama 16 October 2012" } ,
	{ "teamA":"Panama","teamB":"Cuba","matchDate":"20 July 2013","query":"Panama vs Cuba 20 July 2013" } ,
	{ "teamA":"Cuba","teamB":"Trinidad and Tobago","matchDate":"29 November 1990","query":"Cuba vs Trinidad and Tobago 29 November 1990" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Cuba","matchDate":"07 June 1996","query":"Trinidad and Tobago vs Cuba 07 June 1996" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Cuba","matchDate":"20 January 2007","query":"Trinidad and Tobago vs Cuba 20 January 2007" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Cuba","matchDate":"26 November 2010","query":"Trinidad and Tobago vs Cuba 26 November 2010" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Cuba","matchDate":"18 November 2012","query":"Trinidad and Tobago vs Cuba 18 November 2012" } ,
	{ "teamA":"Cuba","teamB":"Trinidad and Tobago","matchDate":"16 December 2012","query":"Cuba vs Trinidad and Tobago 16 December 2012" } ,
	{ "teamA":"Venezuela","teamB":"Cuba","matchDate":"25 November 1990","query":"Venezuela vs Cuba 25 November 1990" } ,
	{ "teamA":"El Salvador","teamB":"Denmark","matchDate":"25 January 2007","query":"El Salvador vs Denmark 25 January 2007" } ,
	{ "teamA":"Denmark","teamB":"Finland","matchDate":"15 November 2011","query":"Denmark vs Finland 15 November 2011" } ,
	{ "teamA":"France","teamB":"Denmark","matchDate":"29 March 2015","query":"France vs Denmark 29 March 2015" } ,
	{ "teamA":"Mexico","teamB":"Denmark","matchDate":"30 January 2013","query":"Mexico vs Denmark 30 January 2013" } ,
	{ "teamA":"Costa Rica","teamB":"Ecuador","matchDate":"10 August 2011","query":"Costa Rica vs Ecuador 10 August 2011" } ,
	{ "teamA":"Ecuador","teamB":"Costa Rica","matchDate":"06 September 2011","query":"Ecuador vs Costa Rica 06 September 2011" } ,
	{ "teamA":"Ecuador","teamB":"El Salvador","matchDate":"27 May 2009","query":"Ecuador vs El Salvador 27 May 2009" } ,
	{ "teamA":"Ecuador","teamB":"El Salvador","matchDate":"21 March 2013","query":"Ecuador vs El Salvador 21 March 2013" } ,
	{ "teamA":"Ecuador","teamB":"Germany","matchDate":"29 May 2013","query":"Ecuador vs Germany 29 May 2013" } ,
	{ "teamA":"Ecuador","teamB":"Greece","matchDate":"07 June 2011","query":"Ecuador vs Greece 07 June 2011" } ,
	{ "teamA":"Ecuador","teamB":"Haiti","matchDate":"26 March 2008","query":"Ecuador vs Haiti 26 March 2008" } ,
	{ "teamA":"Ecuador","teamB":"Haiti","matchDate":"27 March 2008","query":"Ecuador vs Haiti 27 March 2008" } ,
	{ "teamA":"Ecuador","teamB":"Honduras","matchDate":"25 January 2006","query":"Ecuador vs Honduras 25 January 2006" } ,
	{ "teamA":"Honduras","teamB":"Ecuador","matchDate":"09 February 2011","query":"Honduras vs Ecuador 09 February 2011" } ,
	{ "teamA":"Ecuador","teamB":"Honduras","matchDate":"29 February 2012","query":"Ecuador vs Honduras 29 February 2012" } ,
	{ "teamA":"Iran","teamB":"Ecuador","matchDate":"17 December 2008","query":"Iran vs Ecuador 17 December 2008" } ,
	{ "teamA":"Ecuador","teamB":"Jamaica","matchDate":"12 August 2009","query":"Ecuador vs Jamaica 12 August 2009" } ,
	{ "teamA":"Ecuador","teamB":"Jamaica","matchDate":"02 September 2011","query":"Ecuador vs Jamaica 02 September 2011" } ,
	{ "teamA":"Ecuador","teamB":"Mexico","matchDate":"12 November 2008","query":"Ecuador vs Mexico 12 November 2008" } ,
	{ "teamA":"Mexico","teamB":"Ecuador","matchDate":"04 September 2010","query":"Mexico vs Ecuador 04 September 2010" } ,
	{ "teamA":"Mexico","teamB":"Ecuador","matchDate":"28 May 2011","query":"Mexico vs Ecuador 28 May 2011" } ,
	{ "teamA":"Mexico","teamB":"Ecuador","matchDate":"31 May 2014","query":"Mexico vs Ecuador 31 May 2014" } ,
	{ "teamA":"Oman","teamB":"Ecuador","matchDate":"19 December 2008","query":"Oman vs Ecuador 19 December 2008" } ,
	{ "teamA":"Ecuador","teamB":"Paraguay","matchDate":"26 March 2013","query":"Ecuador vs Paraguay 26 March 2013" } ,
	{ "teamA":"Peru","teamB":"Ecuador","matchDate":"29 March 2011","query":"Peru vs Ecuador 29 March 2011" } ,
	{ "teamA":"Peru","teamB":"Ecuador","matchDate":"07 June 2013","query":"Peru vs Ecuador 07 June 2013" } ,
	{ "teamA":"Ecuador","teamB":"Spain","matchDate":"14 August 2013","query":"Ecuador vs Spain 14 August 2013" } ,
	{ "teamA":"Venezuela","teamB":"Ecuador","matchDate":"07 September 2010","query":"Venezuela vs Ecuador 07 September 2010" } ,
	{ "teamA":"Ecuador","teamB":"Venezuela","matchDate":"17 November 2010","query":"Ecuador vs Venezuela 17 November 2010" } ,
	{ "teamA":"Venezuela","teamB":"Ecuador","matchDate":"16 October 2012","query":"Venezuela vs Ecuador 16 October 2012" } ,
	{ "teamA":"Ghana","teamB":"Egypt","matchDate":"31 January 2010","query":"Ghana vs Egypt 31 January 2010" } ,
	{ "teamA":"Ghana","teamB":"Egypt","matchDate":"10 January 2013","query":"Ghana vs Egypt 10 January 2013" } ,
	{ "teamA":"Egypt","teamB":"Ghana","matchDate":"19 November 2013","query":"Egypt vs Ghana 19 November 2013" } ,
	{ "teamA":"Egypt","teamB":"Iraq","matchDate":"17 April 2012","query":"Egypt vs Iraq 17 April 2012" } ,
	{ "teamA":"Iraq","teamB":"Egypt","matchDate":"27 June 2012","query":"Iraq vs Egypt 27 June 2012" } ,
	{ "teamA":"Egypt","teamB":"Ivory Coast","matchDate":"28 January 2006","query":"Egypt vs Ivory Coast 28 January 2006" } ,
	{ "teamA":"Egypt","teamB":"Ivory Coast","matchDate":"10 February 2006","query":"Egypt vs Ivory Coast 10 February 2006" } ,
	{ "teamA":"Ivory Coast","teamB":"Egypt","matchDate":"14 January 2013","query":"Ivory Coast vs Egypt 14 January 2013" } ,
	{ "teamA":"Egypt","teamB":"Morocco","matchDate":"24 January 2006","query":"Egypt vs Morocco 24 January 2006" } ,
	{ "teamA":"Oman","teamB":"Egypt","matchDate":"30 May 2009","query":"Oman vs Egypt 30 May 2009" } ,
	{ "teamA":"Oman","teamB":"Egypt","matchDate":"15 August 2012","query":"Oman vs Egypt 15 August 2012" } ,
	{ "teamA":"Egypt","teamB":"South Africa","matchDate":"14 January 2006","query":"Egypt vs South Africa 14 January 2006" } ,
	{ "teamA":"South Africa","teamB":"Egypt","matchDate":"26 March 2011","query":"South Africa vs Egypt 26 March 2011" } ,
	{ "teamA":"Egypt","teamB":"South Africa","matchDate":"05 June 2011","query":"Egypt vs South Africa 05 June 2011" } ,
	{ "teamA":"South Africa","teamB":"Egypt","matchDate":"06 September 2016","query":"South Africa vs Egypt 06 September 2016" } ,
	{ "teamA":"Egypt","teamB":"Tunisia","matchDate":"16 October 2012","query":"Egypt vs Tunisia 16 October 2012" } ,
	{ "teamA":"United Arab Emirates","teamB":"Egypt","matchDate":"23 February 1988","query":"United Arab Emirates vs Egypt 23 February 1988" } ,
	{ "teamA":"United Arab Emirates","teamB":"Egypt","matchDate":"26 February 1988","query":"United Arab Emirates vs Egypt 26 February 1988" } ,
	{ "teamA":"USA","teamB":"Egypt","matchDate":"20 July 1999","query":"USA vs Egypt 20 July 1999" } ,
	{ "teamA":"Zambia","teamB":"Egypt","matchDate":"10 March 2003","query":"Zambia vs Egypt 10 March 2003" } ,
	{ "teamA":"China PR","teamB":"Estonia","matchDate":"18 December 2010","query":"China PR vs Estonia 18 December 2010" } ,
	{ "teamA":"El Salvador","teamB":"Estonia","matchDate":"29 February 2012","query":"El Salvador vs Estonia 29 February 2012" } ,
	{ "teamA":"Finland","teamB":"Estonia","matchDate":"08 June 2015","query":"Finland vs Estonia 08 June 2015" } ,
	{ "teamA":"France","teamB":"Estonia","matchDate":"05 June 2012","query":"France vs Estonia 05 June 2012" } ,
	{ "teamA":"Estonia","teamB":"Lithuania","matchDate":"31 May 2008","query":"Estonia vs Lithuania 31 May 2008" } ,
	{ "teamA":"Estonia","teamB":"Lithuania","matchDate":"22 November 2008","query":"Estonia vs Lithuania 22 November 2008" } ,
	{ "teamA":"Lithuania","teamB":"Estonia","matchDate":"20 June 2010","query":"Lithuania vs Estonia 20 June 2010" } ,
	{ "teamA":"Estonia","teamB":"Lithuania","matchDate":"03 June 2012","query":"Estonia vs Lithuania 03 June 2012" } ,
	{ "teamA":"Oman","teamB":"Estonia","matchDate":"08 November 2012","query":"Oman vs Estonia 08 November 2012" } ,
	{ "teamA":"Estonia","teamB":"Trinidad and Tobago","matchDate":"07 June 2013","query":"Estonia vs Trinidad and Tobago 07 June 2013" } ,
	{ "teamA":"Turkey","teamB":"Estonia","matchDate":"05 September 2009","query":"Turkey vs Estonia 05 September 2009" } ,
	{ "teamA":"Turkey","teamB":"Estonia","matchDate":"10 August 2011","query":"Turkey vs Estonia 10 August 2011" } ,
	{ "teamA":"United Arab Emirates","teamB":"Estonia","matchDate":"14 November 2012","query":"United Arab Emirates vs Estonia 14 November 2012" } ,
	{ "teamA":"Estonia","teamB":"Uruguay","matchDate":"25 March 2011","query":"Estonia vs Uruguay 25 March 2011" } ,
	{ "teamA":"Uruguay","teamB":"Estonia","matchDate":"23 June 2011","query":"Uruguay vs Estonia 23 June 2011" } ,
	{ "teamA":"Estonia","teamB":"Uzbekistan","matchDate":"07 September 2010","query":"Estonia vs Uzbekistan 07 September 2010" } ,
	{ "teamA":"Israel","teamB":"Finland","matchDate":"06 February 2013","query":"Israel vs Finland 06 February 2013" } ,
	{ "teamA":"Oman","teamB":"Finland","matchDate":"24 January 2014","query":"Oman vs Finland 24 January 2014" } ,
	{ "teamA":"France","teamB":"Costa Rica","matchDate":"09 November 2005","query":"France vs Costa Rica 09 November 2005" } ,
	{ "teamA":"France","teamB":"Uruguay","matchDate":"15 August 2012","query":"France vs Uruguay 15 August 2012" } ,
	{ "teamA":"Germany","teamB":"Lithuania","matchDate":"29 March 2003","query":"Germany vs Lithuania 29 March 2003" } ,
	{ "teamA":"Germany","teamB":"Uruguay","matchDate":"29 May 2011","query":"Germany vs Uruguay 29 May 2011" } ,
	{ "teamA":"China PR","teamB":"Ghana","matchDate":"15 August 2012","query":"China PR vs Ghana 15 August 2012" } ,
	{ "teamA":"Ghana","teamB":"Ivory Coast","matchDate":"16 October 2015","query":"Ghana vs Ivory Coast 16 October 2015" } ,
	{ "teamA":"Ivory Coast","teamB":"Ghana","matchDate":"30 October 2015","query":"Ivory Coast vs Ghana 30 October 2015" } ,
	{ "teamA":"Korea Republic","teamB":"Ghana","matchDate":"07 June 2011","query":"Korea Republic vs Ghana 07 June 2011" } ,
	{ "teamA":"Mexico","teamB":"Ghana","matchDate":"01 March 2006","query":"Mexico vs Ghana 01 March 2006" } ,
	{ "teamA":"Mexico","teamB":"Ghana","matchDate":"26 March 2008","query":"Mexico vs Ghana 26 March 2008" } ,
	{ "teamA":"Saudi Arabia","teamB":"Ghana","matchDate":"17 November 2010","query":"Saudi Arabia vs Ghana 17 November 2010" } ,
	{ "teamA":"South Africa","teamB":"Ghana","matchDate":"15 October 2008","query":"South Africa vs Ghana 15 October 2008" } ,
	{ "teamA":"South Africa","teamB":"Ghana","matchDate":"11 August 2010","query":"South Africa vs Ghana 11 August 2010" } ,
	{ "teamA":"Ghana","teamB":"Tunisia","matchDate":"19 November 2008","query":"Ghana vs Tunisia 19 November 2008" } ,
	{ "teamA":"Ghana","teamB":"Tunisia","matchDate":"05 February 2012","query":"Ghana vs Tunisia 05 February 2012" } ,
	{ "teamA":"Ghana","teamB":"Tunisia","matchDate":"13 January 2013","query":"Ghana vs Tunisia 13 January 2013" } ,
	{ "teamA":"Ghana","teamB":"Zambia","matchDate":"12 August 2009","query":"Ghana vs Zambia 12 August 2009" } ,
	{ "teamA":"Zambia","teamB":"Ghana","matchDate":"08 February 2012","query":"Zambia vs Ghana 08 February 2012" } ,
	{ "teamA":"Zambia","teamB":"Ghana","matchDate":"27 May 2015","query":"Zambia vs Ghana 27 May 2015" } ,
	{ "teamA":"Greece","teamB":"Korea Republic","matchDate":"05 March 2014","query":"Greece vs Korea Republic 05 March 2014" } ,
	{ "teamA":"Greece","teamB":"Lithuania","matchDate":"11 September 2012","query":"Greece vs Lithuania 11 September 2012" } ,
	{ "teamA":"Lithuania","teamB":"Greece","matchDate":"07 June 2013","query":"Lithuania vs Greece 07 June 2013" } ,
	{ "teamA":"Portugal","teamB":"Greece","matchDate":"31 May 2014","query":"Portugal vs Greece 31 May 2014" } ,
	{ "teamA":"Romania","teamB":"Greece","matchDate":"19 November 2013","query":"Romania vs Greece 19 November 2013" } ,
	{ "teamA":"Greece","teamB":"Switzerland","matchDate":"06 February 2013","query":"Greece vs Switzerland 06 February 2013" } ,
	{ "teamA":"Costa Rica","teamB":"Guatemala","matchDate":"25 February 2005","query":"Costa Rica vs Guatemala 25 February 2005" } ,
	{ "teamA":"Guatemala","teamB":"Costa Rica","matchDate":"25 January 2009","query":"Guatemala vs Costa Rica 25 January 2009" } ,
	{ "teamA":"Guatemala","teamB":"Costa Rica","matchDate":"16 January 2011","query":"Guatemala vs Costa Rica 16 January 2011" } ,
	{ "teamA":"Costa Rica","teamB":"Guatemala","matchDate":"25 May 2012","query":"Costa Rica vs Guatemala 25 May 2012" } ,
	{ "teamA":"Costa Rica","teamB":"Guatemala","matchDate":"26 May 2012","query":"Costa Rica vs Guatemala 26 May 2012" } ,
	{ "teamA":"Guatemala","teamB":"Costa Rica","matchDate":"01 June 2012","query":"Guatemala vs Costa Rica 01 June 2012" } ,
	{ "teamA":"Costa Rica","teamB":"Guatemala","matchDate":"22 January 2013","query":"Costa Rica vs Guatemala 22 January 2013" } ,
	{ "teamA":"El Salvador","teamB":"Guatemala","matchDate":"12 February 2007","query":"El Salvador vs Guatemala 12 February 2007" } ,
	{ "teamA":"El Salvador","teamB":"Guatemala","matchDate":"18 February 2007","query":"El Salvador vs Guatemala 18 February 2007" } ,
	{ "teamA":"Guatemala","teamB":"El Salvador","matchDate":"30 May 2008","query":"Guatemala vs El Salvador 30 May 2008" } ,
	{ "teamA":"El Salvador","teamB":"Guatemala","matchDate":"20 July 2008","query":"El Salvador vs Guatemala 20 July 2008" } ,
	{ "teamA":"El Salvador","teamB":"Guatemala","matchDate":"03 March 2010","query":"El Salvador vs Guatemala 03 March 2010" } ,
	{ "teamA":"El Salvador","teamB":"Guatemala","matchDate":"11 August 2012","query":"El Salvador vs Guatemala 11 August 2012" } ,
	{ "teamA":"Guatemala","teamB":"Haiti","matchDate":"03 July 2000","query":"Guatemala vs Haiti 03 July 2000" } ,
	{ "teamA":"Guatemala","teamB":"Haiti","matchDate":"23 April 2008","query":"Guatemala vs Haiti 23 April 2008" } ,
	{ "teamA":"Guatemala","teamB":"Haiti","matchDate":"17 January 2009","query":"Guatemala vs Haiti 17 January 2009" } ,
	{ "teamA":"Honduras","teamB":"Guatemala","matchDate":"12 October 2010","query":"Honduras vs Guatemala 12 October 2010" } ,
	{ "teamA":"Honduras","teamB":"Guatemala","matchDate":"18 January 2011","query":"Honduras vs Guatemala 18 January 2011" } ,
	{ "teamA":"Honduras","teamB":"Guatemala","matchDate":"06 June 2011","query":"Honduras vs Guatemala 06 June 2011" } ,
	{ "teamA":"Jamaica","teamB":"Guatemala","matchDate":"10 June 2011","query":"Jamaica vs Guatemala 10 June 2011" } ,
	{ "teamA":"Jamaica","teamB":"Guatemala","matchDate":"08 June 2012","query":"Jamaica vs Guatemala 08 June 2012" } ,
	{ "teamA":"Guatemala","teamB":"Jamaica","matchDate":"12 October 2012","query":"Guatemala vs Jamaica 12 October 2012" } ,
	{ "teamA":"Japan","teamB":"Guatemala","matchDate":"07 September 2010","query":"Japan vs Guatemala 07 September 2010" } ,
	{ "teamA":"Japan","teamB":"Guatemala","matchDate":"06 September 2013","query":"Japan vs Guatemala 06 September 2013" } ,
	{ "teamA":"Mexico","teamB":"Guatemala","matchDate":"28 June 2009","query":"Mexico vs Guatemala 28 June 2009" } ,
	{ "teamA":"Mexico","teamB":"Guatemala","matchDate":"18 June 2011","query":"Mexico vs Guatemala 18 June 2011" } ,
	{ "teamA":"Panama","teamB":"Guatemala","matchDate":"16 February 2007","query":"Panama vs Guatemala 16 February 2007" } ,
	{ "teamA":"Guatemala","teamB":"Panama","matchDate":"01 June 2008","query":"Guatemala vs Panama 01 June 2008" } ,
	{ "teamA":"Guatemala","teamB":"Panama","matchDate":"27 January 2009","query":"Guatemala vs Panama 27 January 2009" } ,
	{ "teamA":"Panama","teamB":"Guatemala","matchDate":"10 January 2013","query":"Panama vs Guatemala 10 January 2013" } ,
	{ "teamA":"Panama","teamB":"Guatemala","matchDate":"13 January 2013","query":"Panama vs Guatemala 13 January 2013" } ,
	{ "teamA":"Guatemala","teamB":"Panama","matchDate":"25 January 2013","query":"Guatemala vs Panama 25 January 2013" } ,
	{ "teamA":"Paraguay","teamB":"Guatemala","matchDate":"22 February 2012","query":"Paraguay vs Guatemala 22 February 2012" } ,
	{ "teamA":"Guatemala","teamB":"Paraguay","matchDate":"25 April 2012","query":"Guatemala vs Paraguay 25 April 2012" } ,
	{ "teamA":"Paraguay","teamB":"Guatemala","matchDate":"15 August 2012","query":"Paraguay vs Guatemala 15 August 2012" } ,
	{ "teamA":"Paraguay","teamB":"Guatemala","matchDate":"14 November 2012","query":"Paraguay vs Guatemala 14 November 2012" } ,
	{ "teamA":"Venezuela","teamB":"Guatemala","matchDate":"11 February 2009","query":"Venezuela vs Guatemala 11 February 2009" } ,
	{ "teamA":"Guatemala","teamB":"Venezuela","matchDate":"01 June 2011","query":"Guatemala vs Venezuela 01 June 2011" } ,
	{ "teamA":"Guatemala","teamB":"Venezuela","matchDate":"11 October 2014","query":"Guatemala vs Venezuela 11 October 2014" } ,
	{ "teamA":"El Salvador","teamB":"Haiti","matchDate":"09 February 2011","query":"El Salvador vs Haiti 09 February 2011" } ,
	{ "teamA":"El Salvador","teamB":"Haiti","matchDate":"15 July 2013","query":"El Salvador vs Haiti 15 July 2013" } ,
	{ "teamA":"El Salvador","teamB":"Haiti","matchDate":"09 October 2015","query":"El Salvador vs Haiti 09 October 2015" } ,
	{ "teamA":"Honduras","teamB":"Haiti","matchDate":"20 August 2000","query":"Honduras vs Haiti 20 August 2000" } ,
	{ "teamA":"Honduras","teamB":"Haiti","matchDate":"07 June 2008","query":"Honduras vs Haiti 07 June 2008" } ,
	{ "teamA":"Honduras","teamB":"Haiti","matchDate":"04 July 2009","query":"Honduras vs Haiti 04 July 2009" } ,
	{ "teamA":"Jamaica","teamB":"Haiti","matchDate":"22 March 1925","query":"Jamaica vs Haiti 22 March 1925" } ,
	{ "teamA":"Jamaica","teamB":"Haiti","matchDate":"26 March 1925","query":"Jamaica vs Haiti 26 March 1925" } ,
	{ "teamA":"Jamaica","teamB":"Haiti","matchDate":"29 March 1925","query":"Jamaica vs Haiti 29 March 1925" } ,
	{ "teamA":"Haiti","teamB":"Jamaica","matchDate":"13 March 1932","query":"Haiti vs Jamaica 13 March 1932" } ,
	{ "teamA":"Jamaica","teamB":"Haiti","matchDate":"23 May 2009","query":"Jamaica vs Haiti 23 May 2009" } ,
	{ "teamA":"Korea Republic","teamB":"Haiti","matchDate":"06 September 2013","query":"Korea Republic vs Haiti 06 September 2013" } ,
	{ "teamA":"Mexico","teamB":"Haiti","matchDate":"19 July 2009","query":"Mexico vs Haiti 19 July 2009" } ,
	{ "teamA":"Oman","teamB":"Haiti","matchDate":"20 March 2013","query":"Oman vs Haiti 20 March 2013" } ,
	{ "teamA":"Panama","teamB":"Haiti","matchDate":"31 March 2009","query":"Panama vs Haiti 31 March 2009" } ,
	{ "teamA":"Haiti","teamB":"Panama","matchDate":"19 June 2009","query":"Haiti vs Panama 19 June 2009" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Haiti","matchDate":"06 November 2010","query":"Trinidad and Tobago vs Haiti 06 November 2010" } ,
	{ "teamA":"Haiti","teamB":"Trinidad and Tobago","matchDate":"07 December 2012","query":"Haiti vs Trinidad and Tobago 07 December 2012" } ,
	{ "teamA":"Haiti","teamB":"Venezuela","matchDate":"28 September 1999","query":"Haiti vs Venezuela 28 September 1999" } ,
	{ "teamA":"China PR","teamB":"Honduras","matchDate":"12 February 2006","query":"China PR vs Honduras 12 February 2006" } ,
	{ "teamA":"China PR","teamB":"Honduras","matchDate":"29 March 2011","query":"China PR vs Honduras 29 March 2011" } ,
	{ "teamA":"Costa Rica","teamB":"Honduras","matchDate":"09 February 2007","query":"Costa Rica vs Honduras 09 February 2007" } ,
	{ "teamA":"Costa Rica","teamB":"Honduras","matchDate":"14 January 2011","query":"Costa Rica vs Honduras 14 January 2011" } ,
	{ "teamA":"Honduras","teamB":"Costa Rica","matchDate":"23 January 2011","query":"Honduras vs Costa Rica 23 January 2011" } ,
	{ "teamA":"Costa Rica","teamB":"Honduras","matchDate":"18 June 2011","query":"Costa Rica vs Honduras 18 June 2011" } ,
	{ "teamA":"Costa Rica","teamB":"Honduras","matchDate":"11 April 2012","query":"Costa Rica vs Honduras 11 April 2012" } ,
	{ "teamA":"Costa Rica","teamB":"Honduras","matchDate":"27 January 2013","query":"Costa Rica vs Honduras 27 January 2013" } ,
	{ "teamA":"Honduras","teamB":"Costa Rica","matchDate":"21 July 2013","query":"Honduras vs Costa Rica 21 July 2013" } ,
	{ "teamA":"Honduras","teamB":"Costa Rica","matchDate":"11 October 2013","query":"Honduras vs Costa Rica 11 October 2013" } ,
	{ "teamA":"Honduras","teamB":"El Salvador","matchDate":"26 January 2009","query":"Honduras vs El Salvador 26 January 2009" } ,
	{ "teamA":"El Salvador","teamB":"Honduras","matchDate":"01 February 2009","query":"El Salvador vs Honduras 01 February 2009" } ,
	{ "teamA":"El Salvador","teamB":"Honduras","matchDate":"04 September 2010","query":"El Salvador vs Honduras 04 September 2010" } ,
	{ "teamA":"Honduras","teamB":"El Salvador","matchDate":"21 January 2011","query":"Honduras vs El Salvador 21 January 2011" } ,
	{ "teamA":"El Salvador","teamB":"Honduras","matchDate":"29 May 2011","query":"El Salvador vs Honduras 29 May 2011" } ,
	{ "teamA":"El Salvador","teamB":"Honduras","matchDate":"02 June 2012","query":"El Salvador vs Honduras 02 June 2012" } ,
	{ "teamA":"Honduras","teamB":"El Salvador","matchDate":"18 January 2013","query":"Honduras vs El Salvador 18 January 2013" } ,
	{ "teamA":"Honduras","teamB":"Jamaica","matchDate":"13 June 2011","query":"Honduras vs Jamaica 13 June 2011" } ,
	{ "teamA":"Honduras","teamB":"Jamaica","matchDate":"11 October 2011","query":"Honduras vs Jamaica 11 October 2011" } ,
	{ "teamA":"Honduras","teamB":"Jamaica","matchDate":"11 June 2013","query":"Honduras vs Jamaica 11 June 2013" } ,
	{ "teamA":"Jamaica","teamB":"Honduras","matchDate":"15 October 2013","query":"Jamaica vs Honduras 15 October 2013" } ,
	{ "teamA":"Korea Republic","teamB":"Honduras","matchDate":"25 March 2011","query":"Korea Republic vs Honduras 25 March 2011" } ,
	{ "teamA":"Honduras","teamB":"Mexico","matchDate":"22 March 2013","query":"Honduras vs Mexico 22 March 2013" } ,
	{ "teamA":"New Zealand","teamB":"Honduras","matchDate":"09 October 2010","query":"New Zealand vs Honduras 09 October 2010" } ,
	{ "teamA":"Honduras","teamB":"New Zealand","matchDate":"26 May 2012","query":"Honduras vs New Zealand 26 May 2012" } ,
	{ "teamA":"Honduras","teamB":"New Zealand","matchDate":"27 May 2012","query":"Honduras vs New Zealand 27 May 2012" } ,
	{ "teamA":"Honduras","teamB":"Panama","matchDate":"25 February 2005","query":"Honduras vs Panama 25 February 2005" } ,
	{ "teamA":"Panama","teamB":"Honduras","matchDate":"11 February 2007","query":"Panama vs Honduras 11 February 2007" } ,
	{ "teamA":"Honduras","teamB":"Panama","matchDate":"30 January 2009","query":"Honduras vs Panama 30 January 2009" } ,
	{ "teamA":"Panama","teamB":"Honduras","matchDate":"28 June 2009","query":"Panama vs Honduras 28 June 2009" } ,
	{ "teamA":"Panama","teamB":"Honduras","matchDate":"17 November 2010","query":"Panama vs Honduras 17 November 2010" } ,
	{ "teamA":"Honduras","teamB":"Panama","matchDate":"18 December 2010","query":"Honduras vs Panama 18 December 2010" } ,
	{ "teamA":"Honduras","teamB":"Panama","matchDate":"08 June 2012","query":"Honduras vs Panama 08 June 2012" } ,
	{ "teamA":"Panama","teamB":"Honduras","matchDate":"12 October 2012","query":"Panama vs Honduras 12 October 2012" } ,
	{ "teamA":"Honduras","teamB":"Panama","matchDate":"22 January 2013","query":"Honduras vs Panama 22 January 2013" } ,
	{ "teamA":"Panama","teamB":"Honduras","matchDate":"26 March 2013","query":"Panama vs Honduras 26 March 2013" } ,
	{ "teamA":"Honduras","teamB":"Paraguay","matchDate":"06 February 2008","query":"Honduras vs Paraguay 06 February 2008" } ,
	{ "teamA":"Honduras","teamB":"Paraguay","matchDate":"06 September 2011","query":"Honduras vs Paraguay 06 September 2011" } ,
	{ "teamA":"Honduras","teamB":"Peru","matchDate":"18 November 2009","query":"Honduras vs Peru 18 November 2009" } ,
	{ "teamA":"Honduras","teamB":"Peru","matchDate":"15 November 2012","query":"Honduras vs Peru 15 November 2012" } ,
	{ "teamA":"Honduras","teamB":"Serbia","matchDate":"14 November 2011","query":"Honduras vs Serbia 14 November 2011" } ,
	{ "teamA":"Honduras","teamB":"Trinidad and Tobago","matchDate":"15 July 2013","query":"Honduras vs Trinidad and Tobago 15 July 2013" } ,
	{ "teamA":"Turkey","teamB":"Honduras","matchDate":"03 March 2010","query":"Turkey vs Honduras 03 March 2010" } ,
	{ "teamA":"Venezuela","teamB":"Honduras","matchDate":"30 May 2008","query":"Venezuela vs Honduras 30 May 2008" } ,
	{ "teamA":"Honduras","teamB":"Venezuela","matchDate":"10 August 2011","query":"Honduras vs Venezuela 10 August 2011" } ,
	{ "teamA":"Honduras","teamB":"Venezuela","matchDate":"05 March 2014","query":"Honduras vs Venezuela 05 March 2014" } ,
	{ "teamA":"Venezuela","teamB":"Honduras","matchDate":"11 February 2015","query":"Venezuela vs Honduras 11 February 2015" } ,
	{ "teamA":"Venezuela","teamB":"Honduras","matchDate":"04 September 2015","query":"Venezuela vs Honduras 04 September 2015" } ,
	{ "teamA":"Hungary","teamB":"Lithuania","matchDate":"05 June 2015","query":"Hungary vs Lithuania 05 June 2015" } ,
	{ "teamA":"Hungary","teamB":"Sweden","matchDate":"05 September 2009","query":"Hungary vs Sweden 05 September 2009" } ,
	{ "teamA":"Switzerland","teamB":"Iceland","matchDate":"06 September 2013","query":"Switzerland vs Iceland 06 September 2013" } ,
	{ "teamA":"China PR","teamB":"Iran","matchDate":"27 April 1997","query":"China PR vs Iran 27 April 1997" } ,
	{ "teamA":"Iran","teamB":"China PR","matchDate":"19 December 2008","query":"Iran vs China PR 19 December 2008" } ,
	{ "teamA":"Iran","teamB":"China PR","matchDate":"09 January 2009","query":"Iran vs China PR 09 January 2009" } ,
	{ "teamA":"China PR","teamB":"Iran","matchDate":"01 June 2009","query":"China PR vs Iran 01 June 2009" } ,
	{ "teamA":"China PR","teamB":"Iran","matchDate":"03 September 2010","query":"China PR vs Iran 03 September 2010" } ,
	{ "teamA":"Iran","teamB":"Costa Rica","matchDate":"30 January 2008","query":"Iran vs Costa Rica 30 January 2008" } ,
	{ "teamA":"Iran","teamB":"Ecuador","matchDate":"12 January 2000","query":"Iran vs Ecuador 12 January 2000" } ,
	{ "teamA":"Iran","teamB":"Iraq","matchDate":"26 July 2006","query":"Iran vs Iraq 26 July 2006" } ,
	{ "teamA":"Iran","teamB":"Iraq","matchDate":"01 October 2010","query":"Iran vs Iraq 01 October 2010" } ,
	{ "teamA":"Iraq","teamB":"Iran","matchDate":"11 January 2011","query":"Iraq vs Iran 11 January 2011" } ,
	{ "teamA":"Iran","teamB":"Iraq","matchDate":"04 January 2015","query":"Iran vs Iraq 04 January 2015" } ,
	{ "teamA":"Korea DPR","teamB":"Iran","matchDate":"18 September 2003","query":"Korea DPR vs Iran 18 September 2003" } ,
	{ "teamA":"Korea DPR","teamB":"Iran","matchDate":"27 October 2003","query":"Korea DPR vs Iran 27 October 2003" } ,
	{ "teamA":"Iran","teamB":"Korea DPR","matchDate":"02 January 2010","query":"Iran vs Korea DPR 02 January 2010" } ,
	{ "teamA":"Iran","teamB":"Korea DPR","matchDate":"15 January 2011","query":"Iran vs Korea DPR 15 January 2011" } ,
	{ "teamA":"Korea Republic","teamB":"Iran","matchDate":"07 September 2010","query":"Korea Republic vs Iran 07 September 2010" } ,
	{ "teamA":"Iran","teamB":"Korea Republic","matchDate":"22 January 2011","query":"Iran vs Korea Republic 22 January 2011" } ,
	{ "teamA":"Iran","teamB":"Korea Republic","matchDate":"16 October 2012","query":"Iran vs Korea Republic 16 October 2012" } ,
	{ "teamA":"Korea Republic","teamB":"Iran","matchDate":"18 June 2013","query":"Korea Republic vs Iran 18 June 2013" } ,
	{ "teamA":"Oman","teamB":"Iran","matchDate":"28 September 2010","query":"Oman vs Iran 28 September 2010" } ,
	{ "teamA":"Palestine","teamB":"Iran","matchDate":"30 July 2006","query":"Palestine vs Iran 30 July 2006" } ,
	{ "teamA":"Iran","teamB":"Palestine","matchDate":"05 October 2011","query":"Iran vs Palestine 05 October 2011" } ,
	{ "teamA":"Tunisia","teamB":"Iran","matchDate":"15 August 2012","query":"Tunisia vs Iran 15 August 2012" } ,
	{ "teamA":"Iran","teamB":"United Arab Emirates","matchDate":"28 July 2006","query":"Iran vs United Arab Emirates 28 July 2006" } ,
	{ "teamA":"United Arab Emirates","teamB":"Iran","matchDate":"19 January 2011","query":"United Arab Emirates vs Iran 19 January 2011" } ,
	{ "teamA":"Uzbekistan","teamB":"Iran","matchDate":"05 September 2009","query":"Uzbekistan vs Iran 05 September 2009" } ,
	{ "teamA":"Uzbekistan","teamB":"Iran","matchDate":"03 June 2012","query":"Uzbekistan vs Iran 03 June 2012" } ,
	{ "teamA":"Iran","teamB":"Uzbekistan","matchDate":"14 November 2012","query":"Iran vs Uzbekistan 14 November 2012" } ,
	{ "teamA":"Uzbekistan","teamB":"Iran","matchDate":"11 June 2015","query":"Uzbekistan vs Iran 11 June 2015" } ,
	{ "teamA":"Iran","teamB":"Zambia","matchDate":"25 May 2008","query":"Iran vs Zambia 25 May 2008" } ,
	{ "teamA":"China PR","teamB":"Iraq","matchDate":"11 October 2011","query":"China PR vs Iraq 11 October 2011" } ,
	{ "teamA":"Iraq","teamB":"China PR","matchDate":"11 November 2011","query":"Iraq vs China PR 11 November 2011" } ,
	{ "teamA":"China PR","teamB":"Iraq","matchDate":"22 March 2013","query":"China PR vs Iraq 22 March 2013" } ,
	{ "teamA":"Japan","teamB":"Iraq","matchDate":"11 September 2012","query":"Japan vs Iraq 11 September 2012" } ,
	{ "teamA":"Iraq","teamB":"Japan","matchDate":"11 June 2013","query":"Iraq vs Japan 11 June 2013" } ,
	{ "teamA":"Iraq","teamB":"Korea DPR","matchDate":"19 January 2011","query":"Iraq vs Korea DPR 19 January 2011" } ,
	{ "teamA":"Korea DPR","teamB":"Iraq","matchDate":"26 March 2011","query":"Korea DPR vs Iraq 26 March 2011" } ,
	{ "teamA":"Korea Republic","teamB":"Iraq","matchDate":"29 June 2007","query":"Korea Republic vs Iraq 29 June 2007" } ,
	{ "teamA":"Korea Republic","teamB":"Iraq","matchDate":"28 March 2009","query":"Korea Republic vs Iraq 28 March 2009" } ,
	{ "teamA":"Morocco","teamB":"Iraq","matchDate":"03 July 2012","query":"Morocco vs Iraq 03 July 2012" } ,
	{ "teamA":"Oman","teamB":"Iraq","matchDate":"07 October 2004","query":"Oman vs Iraq 07 October 2004" } ,
	{ "teamA":"Oman","teamB":"Iraq","matchDate":"13 February 2006","query":"Oman vs Iraq 13 February 2006" } ,
	{ "teamA":"Oman","teamB":"Iraq","matchDate":"07 January 2009","query":"Oman vs Iraq 07 January 2009" } ,
	{ "teamA":"Iraq","teamB":"Oman","matchDate":"21 September 2010","query":"Iraq vs Oman 21 September 2010" } ,
	{ "teamA":"Oman","teamB":"Iraq","matchDate":"29 November 2010","query":"Oman vs Iraq 29 November 2010" } ,
	{ "teamA":"Iraq","teamB":"Oman","matchDate":"12 June 2012","query":"Iraq vs Oman 12 June 2012" } ,
	{ "teamA":"Oman","teamB":"Iraq","matchDate":"18 December 2012","query":"Oman vs Iraq 18 December 2012" } ,
	{ "teamA":"Oman","teamB":"Iraq","matchDate":"04 June 2013","query":"Oman vs Iraq 04 June 2013" } ,
	{ "teamA":"Iraq","teamB":"Palestine","matchDate":"01 December 2005","query":"Iraq vs Palestine 01 December 2005" } ,
	{ "teamA":"Palestine","teamB":"Iraq","matchDate":"28 July 2006","query":"Palestine vs Iraq 28 July 2006" } ,
	{ "teamA":"Iraq","teamB":"Palestine","matchDate":"10 July 2009","query":"Iraq vs Palestine 10 July 2009" } ,
	{ "teamA":"Iraq","teamB":"Palestine","matchDate":"13 July 2009","query":"Iraq vs Palestine 13 July 2009" } ,
	{ "teamA":"Palestine","teamB":"Iraq","matchDate":"29 September 2010","query":"Palestine vs Iraq 29 September 2010" } ,
	{ "teamA":"Saudi Arabia","teamB":"Iraq","matchDate":"24 January 2007","query":"Saudi Arabia vs Iraq 24 January 2007" } ,
	{ "teamA":"Saudi Arabia","teamB":"Iraq","matchDate":"22 March 2009","query":"Saudi Arabia vs Iraq 22 March 2009" } ,
	{ "teamA":"Saudi Arabia","teamB":"Iraq","matchDate":"28 December 2010","query":"Saudi Arabia vs Iraq 28 December 2010" } ,
	{ "teamA":"Saudi Arabia","teamB":"Iraq","matchDate":"05 July 2012","query":"Saudi Arabia vs Iraq 05 July 2012" } ,
	{ "teamA":"Saudi Arabia","teamB":"Iraq","matchDate":"06 January 2013","query":"Saudi Arabia vs Iraq 06 January 2013" } ,
	{ "teamA":"Iraq","teamB":"Saudi Arabia","matchDate":"15 October 2013","query":"Iraq vs Saudi Arabia 15 October 2013" } ,
	{ "teamA":"Saudi Arabia","teamB":"Iraq","matchDate":"15 November 2013","query":"Saudi Arabia vs Iraq 15 November 2013" } ,
	{ "teamA":"South Africa","teamB":"Iraq","matchDate":"14 June 2009","query":"South Africa vs Iraq 14 June 2009" } ,
	{ "teamA":"Iraq","teamB":"Tunisia","matchDate":"30 December 2012","query":"Iraq vs Tunisia 30 December 2012" } ,
	{ "teamA":"Iraq","teamB":"United Arab Emirates","matchDate":"30 July 2006","query":"Iraq vs United Arab Emirates 30 July 2006" } ,
	{ "teamA":"United Arab Emirates","teamB":"Iraq","matchDate":"31 January 2008","query":"United Arab Emirates vs Iraq 31 January 2008" } ,
	{ "teamA":"United Arab Emirates","teamB":"Iraq","matchDate":"27 December 2008","query":"United Arab Emirates vs Iraq 27 December 2008" } ,
	{ "teamA":"United Arab Emirates","teamB":"Iraq","matchDate":"18 November 2009","query":"United Arab Emirates vs Iraq 18 November 2009" } ,
	{ "teamA":"Iraq","teamB":"United Arab Emirates","matchDate":"23 November 2010","query":"Iraq vs United Arab Emirates 23 November 2010" } ,
	{ "teamA":"United Arab Emirates","teamB":"Iraq","matchDate":"15 January 2011","query":"United Arab Emirates vs Iraq 15 January 2011" } ,
	{ "teamA":"United Arab Emirates","teamB":"Iraq","matchDate":"18 January 2013","query":"United Arab Emirates vs Iraq 18 January 2013" } ,
	{ "teamA":"Iraq","teamB":"United Arab Emirates","matchDate":"30 January 2015","query":"Iraq vs United Arab Emirates 30 January 2015" } ,
	{ "teamA":"Iraq","teamB":"Uzbekistan","matchDate":"02 July 2007","query":"Iraq vs Uzbekistan 02 July 2007" } ,
	{ "teamA":"Uzbekistan","teamB":"Iraq","matchDate":"25 December 2014","query":"Uzbekistan vs Iraq 25 December 2014" } ,
	{ "teamA":"Iraq","teamB":"Uzbekistan","matchDate":"28 December 2014","query":"Iraq vs Uzbekistan 28 December 2014" } ,
	{ "teamA":"Uzbekistan","teamB":"Iraq","matchDate":"28 December 2014","query":"Uzbekistan vs Iraq 28 December 2014" } ,
	{ "teamA":"Israel","teamB":"Ivory Coast","matchDate":"19 November 2008","query":"Israel vs Ivory Coast 19 November 2008" } ,
	{ "teamA":"Ivory Coast","teamB":"Israel","matchDate":"10 August 2011","query":"Ivory Coast vs Israel 10 August 2011" } ,
	{ "teamA":"Israel","teamB":"Portugal","matchDate":"22 March 2013","query":"Israel vs Portugal 22 March 2013" } ,
	{ "teamA":"Portugal","teamB":"Israel","matchDate":"11 October 2013","query":"Portugal vs Israel 11 October 2013" } ,
	{ "teamA":"Israel","teamB":"Serbia","matchDate":"09 February 2011","query":"Israel vs Serbia 09 February 2011" } ,
	{ "teamA":"Italy","teamB":"Portugal","matchDate":"16 June 2015","query":"Italy vs Portugal 16 June 2015" } ,
	{ "teamA":"China PR","teamB":"Jamaica","matchDate":"10 August 2011","query":"China PR vs Jamaica 10 August 2011" } ,
	{ "teamA":"Jamaica","teamB":"Costa Rica","matchDate":"06 February 2008","query":"Jamaica vs Costa Rica 06 February 2008" } ,
	{ "teamA":"Jamaica","teamB":"Costa Rica","matchDate":"07 July 2009","query":"Jamaica vs Costa Rica 07 July 2009" } ,
	{ "teamA":"Jamaica","teamB":"Costa Rica","matchDate":"05 September 2010","query":"Jamaica vs Costa Rica 05 September 2010" } ,
	{ "teamA":"Jamaica","teamB":"Costa Rica","matchDate":"17 November 2010","query":"Jamaica vs Costa Rica 17 November 2010" } ,
	{ "teamA":"Jamaica","teamB":"Costa Rica","matchDate":"21 March 2012","query":"Jamaica vs Costa Rica 21 March 2012" } ,
	{ "teamA":"Costa Rica","teamB":"Jamaica","matchDate":"26 March 2013","query":"Costa Rica vs Jamaica 26 March 2013" } ,
	{ "teamA":"Jamaica","teamB":"El Salvador","matchDate":"30 May 2009","query":"Jamaica vs El Salvador 30 May 2009" } ,
	{ "teamA":"El Salvador","teamB":"Jamaica","matchDate":"10 July 2009","query":"El Salvador vs Jamaica 10 July 2009" } ,
	{ "teamA":"El Salvador","teamB":"Jamaica","matchDate":"29 March 2011","query":"El Salvador vs Jamaica 29 March 2011" } ,
	{ "teamA":"El Salvador","teamB":"Jamaica","matchDate":"15 August 2012","query":"El Salvador vs Jamaica 15 August 2012" } ,
	{ "teamA":"Korea Republic","teamB":"Jamaica","matchDate":"13 October 2015","query":"Korea Republic vs Jamaica 13 October 2015" } ,
	{ "teamA":"Jamaica","teamB":"Mexico","matchDate":"20 December 1995","query":"Jamaica vs Mexico 20 December 1995" } ,
	{ "teamA":"Mexico","teamB":"Jamaica","matchDate":"06 February 2013","query":"Mexico vs Jamaica 06 February 2013" } ,
	{ "teamA":"Jamaica","teamB":"Mexico","matchDate":"04 June 2013","query":"Jamaica vs Mexico 04 June 2013" } ,
	{ "teamA":"New Zealand","teamB":"Jamaica","matchDate":"29 February 2012","query":"New Zealand vs Jamaica 29 February 2012" } ,
	{ "teamA":"Jamaica","teamB":"Panama","matchDate":"07 June 2009","query":"Jamaica vs Panama 07 June 2009" } ,
	{ "teamA":"Jamaica","teamB":"Panama","matchDate":"27 May 2012","query":"Jamaica vs Panama 27 May 2012" } ,
	{ "teamA":"Panama","teamB":"Jamaica","matchDate":"01 June 2012","query":"Panama vs Jamaica 01 June 2012" } ,
	{ "teamA":"Jamaica","teamB":"Panama","matchDate":"22 March 2013","query":"Jamaica vs Panama 22 March 2013" } ,
	{ "teamA":"Jamaica","teamB":"Peru","matchDate":"07 September 2010","query":"Jamaica vs Peru 07 September 2010" } ,
	{ "teamA":"Switzerland","teamB":"Jamaica","matchDate":"30 May 2014","query":"Switzerland vs Jamaica 30 May 2014" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Jamaica","matchDate":"03 November 1947","query":"Trinidad and Tobago vs Jamaica 03 November 1947" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Jamaica","matchDate":"08 November 1947","query":"Trinidad and Tobago vs Jamaica 08 November 1947" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Jamaica","matchDate":"12 November 1947","query":"Trinidad and Tobago vs Jamaica 12 November 1947" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Jamaica","matchDate":"04 May 1958","query":"Trinidad and Tobago vs Jamaica 04 May 1958" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Jamaica","matchDate":"11 May 1958","query":"Trinidad and Tobago vs Jamaica 11 May 1958" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Jamaica","matchDate":"13 May 1958","query":"Trinidad and Tobago vs Jamaica 13 May 1958" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Jamaica","matchDate":"10 March 1959","query":"Trinidad and Tobago vs Jamaica 10 March 1959" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Jamaica","matchDate":"25 November 1967","query":"Trinidad and Tobago vs Jamaica 25 November 1967" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Jamaica","matchDate":"02 December 1967","query":"Trinidad and Tobago vs Jamaica 02 December 1967" } ,
	{ "teamA":"Jamaica","teamB":"Trinidad and Tobago","matchDate":"28 May 1993","query":"Jamaica vs Trinidad and Tobago 28 May 1993" } ,
	{ "teamA":"Jamaica","teamB":"Trinidad and Tobago","matchDate":"27 March 2008","query":"Jamaica vs Trinidad and Tobago 27 March 2008" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Jamaica","matchDate":"07 June 2008","query":"Trinidad and Tobago vs Jamaica 07 June 2008" } ,
	{ "teamA":"Jamaica","teamB":"Trinidad and Tobago","matchDate":"07 December 2008","query":"Jamaica vs Trinidad and Tobago 07 December 2008" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Jamaica","matchDate":"11 August 2010","query":"Trinidad and Tobago vs Jamaica 11 August 2010" } ,
	{ "teamA":"Jamaica","teamB":"Trinidad and Tobago","matchDate":"10 October 2010","query":"Jamaica vs Trinidad and Tobago 10 October 2010" } ,
	{ "teamA":"Jamaica","teamB":"Trinidad and Tobago","matchDate":"15 November 2013","query":"Jamaica vs Trinidad and Tobago 15 November 2013" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Jamaica","matchDate":"19 November 2013","query":"Trinidad and Tobago vs Jamaica 19 November 2013" } ,
	{ "teamA":"Jamaica","teamB":"Venezuela","matchDate":"25 March 2011","query":"Jamaica vs Venezuela 25 March 2011" } ,
	{ "teamA":"Japan","teamB":"Bosnia and Herzegovina","matchDate":"07 June 2016","query":"Japan vs Bosnia and Herzegovina 07 June 2016" } ,
	{ "teamA":"Japan","teamB":"China PR","matchDate":"21 July 2013","query":"Japan vs China PR 21 July 2013" } ,
	{ "teamA":"Costa Rica","teamB":"Japan","matchDate":"01 June 2014","query":"Costa Rica vs Japan 01 June 2014" } ,
	{ "teamA":"Korea DPR","teamB":"Japan","matchDate":"15 November 2011","query":"Korea DPR vs Japan 15 November 2011" } ,
	{ "teamA":"Korea DPR","teamB":"Japan","matchDate":"02 August 2015","query":"Korea DPR vs Japan 02 August 2015" } ,
	{ "teamA":"Korea Republic","teamB":"Japan","matchDate":"12 October 2010","query":"Korea Republic vs Japan 12 October 2010" } ,
	{ "teamA":"Japan","teamB":"Korea Republic","matchDate":"25 January 2011","query":"Japan vs Korea Republic 25 January 2011" } ,
	{ "teamA":"Japan","teamB":"Korea Republic","matchDate":"10 August 2011","query":"Japan vs Korea Republic 10 August 2011" } ,
	{ "teamA":"Japan","teamB":"Oman","matchDate":"03 June 2012","query":"Japan vs Oman 03 June 2012" } ,
	{ "teamA":"Oman","teamB":"Japan","matchDate":"14 November 2012","query":"Oman vs Japan 14 November 2012" } ,
	{ "teamA":"Japan","teamB":"Paraguay","matchDate":"04 September 2010","query":"Japan vs Paraguay 04 September 2010" } ,
	{ "teamA":"Japan","teamB":"Peru","matchDate":"01 June 2011","query":"Japan vs Peru 01 June 2011" } ,
	{ "teamA":"Saudi Arabia","teamB":"Japan","matchDate":"17 January 2011","query":"Saudi Arabia vs Japan 17 January 2011" } ,
	{ "teamA":"Serbia","teamB":"Japan","matchDate":"11 October 2013","query":"Serbia vs Japan 11 October 2013" } ,
	{ "teamA":"Japan","teamB":"Trinidad and Tobago","matchDate":"09 August 2006","query":"Japan vs Trinidad and Tobago 09 August 2006" } ,
	{ "teamA":"Japan","teamB":"Tunisia","matchDate":"27 March 2015","query":"Japan vs Tunisia 27 March 2015" } ,
	{ "teamA":"Japan","teamB":"United Arab Emirates","matchDate":"09 October 2008","query":"Japan vs United Arab Emirates 09 October 2008" } ,
	{ "teamA":"Japan","teamB":"United Arab Emirates","matchDate":"06 September 2012","query":"Japan vs United Arab Emirates 06 September 2012" } ,
	{ "teamA":"Japan","teamB":"Uruguay","matchDate":"14 August 2013","query":"Japan vs Uruguay 14 August 2013" } ,
	{ "teamA":"Japan","teamB":"Venezuela","matchDate":"15 August 2012","query":"Japan vs Venezuela 15 August 2012" } ,
	{ "teamA":"Lithuania","teamB":"Romania","matchDate":"06 June 2009","query":"Lithuania vs Romania 06 June 2009" } ,
	{ "teamA":"Mexico","teamB":"Bosnia and Herzegovina","matchDate":"09 February 2011","query":"Mexico vs Bosnia and Herzegovina 09 February 2011" } ,
	{ "teamA":"Mexico","teamB":"China PR","matchDate":"16 April 2008","query":"Mexico vs China PR 16 April 2008" } ,
	{ "teamA":"Mexico","teamB":"Costa Rica","matchDate":"12 June 2011","query":"Mexico vs Costa Rica 12 June 2011" } ,
	{ "teamA":"Costa Rica","teamB":"Mexico","matchDate":"15 October 2013","query":"Costa Rica vs Mexico 15 October 2013" } ,
	{ "teamA":"Mexico","teamB":"El Salvador","matchDate":"05 June 2011","query":"Mexico vs El Salvador 05 June 2011" } ,
	{ "teamA":"Mexico","teamB":"El Salvador","matchDate":"16 October 2012","query":"Mexico vs El Salvador 16 October 2012" } ,
	{ "teamA":"Mexico","teamB":"Ivory Coast","matchDate":"15 August 2013","query":"Mexico vs Ivory Coast 15 August 2013" } ,
	{ "teamA":"Mexico","teamB":"Korea Republic","matchDate":"29 January 2014","query":"Mexico vs Korea Republic 29 January 2014" } ,
	{ "teamA":"Mexico","teamB":"Korea Republic","matchDate":"30 January 2014","query":"Mexico vs Korea Republic 30 January 2014" } ,
	{ "teamA":"Mexico","teamB":"New Zealand","matchDate":"01 June 2011","query":"Mexico vs New Zealand 01 June 2011" } ,
	{ "teamA":"Mexico","teamB":"New Zealand","matchDate":"13 November 2013","query":"Mexico vs New Zealand 13 November 2013" } ,
	{ "teamA":"Mexico","teamB":"Panama","matchDate":"09 July 2009","query":"Mexico vs Panama 09 July 2009" } ,
	{ "teamA":"Panama","teamB":"Mexico","matchDate":"07 June 2013","query":"Panama vs Mexico 07 June 2013" } ,
	{ "teamA":"Mexico","teamB":"Panama","matchDate":"24 July 2013","query":"Mexico vs Panama 24 July 2013" } ,
	{ "teamA":"Mexico","teamB":"Paraguay","matchDate":"26 March 2011","query":"Mexico vs Paraguay 26 March 2011" } ,
	{ "teamA":"Mexico","teamB":"Paraguay","matchDate":"28 May 2016","query":"Mexico vs Paraguay 28 May 2016" } ,
	{ "teamA":"Mexico","teamB":"Serbia","matchDate":"11 November 2011","query":"Mexico vs Serbia 11 November 2011" } ,
	{ "teamA":"Mexico","teamB":"Spain","matchDate":"11 August 2010","query":"Mexico vs Spain 11 August 2010" } ,
	{ "teamA":"Mexico","teamB":"Trinidad and Tobago","matchDate":"20 July 2013","query":"Mexico vs Trinidad and Tobago 20 July 2013" } ,
	{ "teamA":"Mexico","teamB":"Trinidad and Tobago","matchDate":"04 September 2015","query":"Mexico vs Trinidad and Tobago 04 September 2015" } ,
	{ "teamA":"Uruguay","teamB":"Mexico","matchDate":"12 July 2011","query":"Uruguay vs Mexico 12 July 2011" } ,
	{ "teamA":"Mexico","teamB":"Venezuela","matchDate":"24 June 2009","query":"Mexico vs Venezuela 24 June 2009" } ,
	{ "teamA":"Mexico","teamB":"Venezuela","matchDate":"12 October 2010","query":"Mexico vs Venezuela 12 October 2010" } ,
	{ "teamA":"Mexico","teamB":"Venezuela","matchDate":"29 March 2011","query":"Mexico vs Venezuela 29 March 2011" } ,
	{ "teamA":"Mexico","teamB":"Venezuela","matchDate":"25 January 2012","query":"Mexico vs Venezuela 25 January 2012" } ,
	{ "teamA":"Mexico","teamB":"Wales","matchDate":"27 May 2012","query":"Mexico vs Wales 27 May 2012" } ,
	{ "teamA":"Morocco","teamB":"Ivory Coast","matchDate":"21 January 2006","query":"Morocco vs Ivory Coast 21 January 2006" } ,
	{ "teamA":"Morocco","teamB":"Ivory Coast","matchDate":"09 June 2012","query":"Morocco vs Ivory Coast 09 June 2012" } ,
	{ "teamA":"Morocco","teamB":"Ivory Coast","matchDate":"09 October 2015","query":"Morocco vs Ivory Coast 09 October 2015" } ,
	{ "teamA":"Oman","teamB":"Morocco","matchDate":"06 September 2008","query":"Oman vs Morocco 06 September 2008" } ,
	{ "teamA":"Morocco","teamB":"Saudi Arabia","matchDate":"18 March 2003","query":"Morocco vs Saudi Arabia 18 March 2003" } ,
	{ "teamA":"Morocco","teamB":"South Africa","matchDate":"27 January 2013","query":"Morocco vs South Africa 27 January 2013" } ,
	{ "teamA":"Morocco","teamB":"South Africa","matchDate":"11 October 2013","query":"Morocco vs South Africa 11 October 2013" } ,
	{ "teamA":"Morocco","teamB":"Tunisia","matchDate":"23 January 2012","query":"Morocco vs Tunisia 23 January 2012" } ,
	{ "teamA":"Tunisia","teamB":"Morocco","matchDate":"06 July 2013","query":"Tunisia vs Morocco 06 July 2013" } ,
	{ "teamA":"Morocco","teamB":"Tunisia","matchDate":"13 July 2013","query":"Morocco vs Tunisia 13 July 2013" } ,
	{ "teamA":"Morocco","teamB":"Tunisia","matchDate":"14 July 2013","query":"Morocco vs Tunisia 14 July 2013" } ,
	{ "teamA":"Morocco","teamB":"Tunisia","matchDate":"15 June 2015","query":"Morocco vs Tunisia 15 June 2015" } ,
	{ "teamA":"Tunisia","teamB":"Morocco","matchDate":"25 October 2015","query":"Tunisia vs Morocco 25 October 2015" } ,
	{ "teamA":"Morocco","teamB":"Uruguay","matchDate":"28 March 2015","query":"Morocco vs Uruguay 28 March 2015" } ,
	{ "teamA":"Morocco","teamB":"Zambia","matchDate":"19 November 2008","query":"Morocco vs Zambia 19 November 2008" } ,
	{ "teamA":"Zambia","teamB":"Morocco","matchDate":"08 January 2013","query":"Zambia vs Morocco 08 January 2013" } ,
	{ "teamA":"Oman","teamB":"China PR","matchDate":"17 December 2008","query":"Oman vs China PR 17 December 2008" } ,
	{ "teamA":"China PR","teamB":"Oman","matchDate":"03 January 2015","query":"China PR vs Oman 03 January 2015" } ,
	{ "teamA":"Oman","teamB":"New Zealand","matchDate":"12 November 2015","query":"Oman vs New Zealand 12 November 2015" } ,
	{ "teamA":"Oman","teamB":"Palestine","matchDate":"14 December 2012","query":"Oman vs Palestine 14 December 2012" } ,
	{ "teamA":"Oman","teamB":"Paraguay","matchDate":"19 November 2008","query":"Oman vs Paraguay 19 November 2008" } ,
	{ "teamA":"Republic of Ireland","teamB":"Oman","matchDate":"31 August 2016","query":"Republic of Ireland vs Oman 31 August 2016" } ,
	{ "teamA":"Oman","teamB":"Romania","matchDate":"08 January 2002","query":"Oman vs Romania 08 January 2002" } ,
	{ "teamA":"Oman","teamB":"Saudi Arabia","matchDate":"17 January 2009","query":"Oman vs Saudi Arabia 17 January 2009" } ,
	{ "teamA":"Oman","teamB":"Saudi Arabia","matchDate":"12 August 2009","query":"Oman vs Saudi Arabia 12 August 2009" } ,
	{ "teamA":"Oman","teamB":"Saudi Arabia","matchDate":"02 September 2011","query":"Oman vs Saudi Arabia 02 September 2011" } ,
	{ "teamA":"Saudi Arabia","teamB":"Oman","matchDate":"15 November 2011","query":"Saudi Arabia vs Oman 15 November 2011" } ,
	{ "teamA":"Oman","teamB":"Tunisia","matchDate":"29 March 2011","query":"Oman vs Tunisia 29 March 2011" } ,
	{ "teamA":"Oman","teamB":"United Arab Emirates","matchDate":"16 November 1994","query":"Oman vs United Arab Emirates 16 November 1994" } ,
	{ "teamA":"United Arab Emirates","teamB":"Oman","matchDate":"11 October 2005","query":"United Arab Emirates vs Oman 11 October 2005" } ,
	{ "teamA":"United Arab Emirates","teamB":"Oman","matchDate":"12 October 2005","query":"United Arab Emirates vs Oman 12 October 2005" } ,
	{ "teamA":"United Arab Emirates","teamB":"Oman","matchDate":"17 January 2007","query":"United Arab Emirates vs Oman 17 January 2007" } ,
	{ "teamA":"Oman","teamB":"United Arab Emirates","matchDate":"30 January 2007","query":"Oman vs United Arab Emirates 30 January 2007" } ,
	{ "teamA":"Oman","teamB":"United Arab Emirates","matchDate":"19 March 2008","query":"Oman vs United Arab Emirates 19 March 2008" } ,
	{ "teamA":"Oman","teamB":"United Arab Emirates","matchDate":"26 November 2010","query":"Oman vs United Arab Emirates 26 November 2010" } ,
	{ "teamA":"United Arab Emirates","teamB":"Oman","matchDate":"11 January 2013","query":"United Arab Emirates vs Oman 11 January 2013" } ,
	{ "teamA":"Oman","teamB":"United Arab Emirates","matchDate":"25 November 2014","query":"Oman vs United Arab Emirates 25 November 2014" } ,
	{ "teamA":"Oman","teamB":"Uzbekistan","matchDate":"20 August 2008","query":"Oman vs Uzbekistan 20 August 2008" } ,
	{ "teamA":"Uzbekistan","teamB":"Oman","matchDate":"27 May 2014","query":"Uzbekistan vs Oman 27 May 2014" } ,
	{ "teamA":"Uzbekistan","teamB":"Oman","matchDate":"29 May 2014","query":"Uzbekistan vs Oman 29 May 2014" } ,
	{ "teamA":"Oman","teamB":"Zambia","matchDate":"24 September 1998","query":"Oman vs Zambia 24 September 1998" } ,
	{ "teamA":"China PR","teamB":"Palestine","matchDate":"18 July 2009","query":"China PR vs Palestine 18 July 2009" } ,
	{ "teamA":"China PR","teamB":"Palestine","matchDate":"21 December 2014","query":"China PR vs Palestine 21 December 2014" } ,
	{ "teamA":"Korea DPR","teamB":"Palestine","matchDate":"16 March 2012","query":"Korea DPR vs Palestine 16 March 2012" } ,
	{ "teamA":"Saudi Arabia","teamB":"Palestine","matchDate":"28 June 2012","query":"Saudi Arabia vs Palestine 28 June 2012" } ,
	{ "teamA":"Saudi Arabia","teamB":"Palestine","matchDate":"11 June 2015","query":"Saudi Arabia vs Palestine 11 June 2015" } ,
	{ "teamA":"Palestine","teamB":"United Arab Emirates","matchDate":"26 July 2006","query":"Palestine vs United Arab Emirates 26 July 2006" } ,
	{ "teamA":"United Arab Emirates","teamB":"Palestine","matchDate":"10 October 2009","query":"United Arab Emirates vs Palestine 10 October 2009" } ,
	{ "teamA":"United Arab Emirates","teamB":"Palestine","matchDate":"24 February 2012","query":"United Arab Emirates vs Palestine 24 February 2012" } ,
	{ "teamA":"Palestine","teamB":"United Arab Emirates","matchDate":"08 September 2015","query":"Palestine vs United Arab Emirates 08 September 2015" } ,
	{ "teamA":"Uzbekistan","teamB":"Palestine","matchDate":"13 December 2014","query":"Uzbekistan vs Palestine 13 December 2014" } ,
	{ "teamA":"Panama","teamB":"Costa Rica","matchDate":"23 February 2005","query":"Panama vs Costa Rica 23 February 2005" } ,
	{ "teamA":"Panama","teamB":"Costa Rica","matchDate":"13 February 2007","query":"Panama vs Costa Rica 13 February 2007" } ,
	{ "teamA":"Costa Rica","teamB":"Panama","matchDate":"18 February 2007","query":"Costa Rica vs Panama 18 February 2007" } ,
	{ "teamA":"Costa Rica","teamB":"Panama","matchDate":"23 January 2009","query":"Costa Rica vs Panama 23 January 2009" } ,
	{ "teamA":"Costa Rica","teamB":"Panama","matchDate":"01 February 2009","query":"Costa Rica vs Panama 01 February 2009" } ,
	{ "teamA":"Panama","teamB":"Costa Rica","matchDate":"03 September 2010","query":"Panama vs Costa Rica 03 September 2010" } ,
	{ "teamA":"Panama","teamB":"Costa Rica","matchDate":"21 January 2011","query":"Panama vs Costa Rica 21 January 2011" } ,
	{ "teamA":"Panama","teamB":"Costa Rica","matchDate":"11 November 2011","query":"Panama vs Costa Rica 11 November 2011" } ,
	{ "teamA":"Costa Rica","teamB":"Panama","matchDate":"18 June 2013","query":"Costa Rica vs Panama 18 June 2013" } ,
	{ "teamA":"El Salvador","teamB":"Panama","matchDate":"19 February 2005","query":"El Salvador vs Panama 19 February 2005" } ,
	{ "teamA":"El Salvador","teamB":"Panama","matchDate":"29 November 2006","query":"El Salvador vs Panama 29 November 2006" } ,
	{ "teamA":"Panama","teamB":"El Salvador","matchDate":"08 October 2010","query":"Panama vs El Salvador 08 October 2010" } ,
	{ "teamA":"Panama","teamB":"El Salvador","matchDate":"18 January 2011","query":"Panama vs El Salvador 18 January 2011" } ,
	{ "teamA":"Panama","teamB":"El Salvador","matchDate":"23 January 2011","query":"Panama vs El Salvador 23 January 2011" } ,
	{ "teamA":"Panama","teamB":"El Salvador","matchDate":"19 June 2011","query":"Panama vs El Salvador 19 June 2011" } ,
	{ "teamA":"El Salvador","teamB":"Panama","matchDate":"20 January 2013","query":"El Salvador vs Panama 20 January 2013" } ,
	{ "teamA":"Panama","teamB":"Paraguay","matchDate":"02 September 2011","query":"Panama vs Paraguay 02 September 2011" } ,
	{ "teamA":"Paraguay","teamB":"Panama","matchDate":"29 February 2012","query":"Paraguay vs Panama 29 February 2012" } ,
	{ "teamA":"Panama","teamB":"Peru","matchDate":"12 October 2010","query":"Panama vs Peru 12 October 2010" } ,
	{ "teamA":"Peru","teamB":"Panama","matchDate":"08 February 2011","query":"Peru vs Panama 08 February 2011" } ,
	{ "teamA":"Peru","teamB":"Panama","matchDate":"06 August 2014","query":"Peru vs Panama 06 August 2014" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Panama","matchDate":"11 October 2006","query":"Trinidad and Tobago vs Panama 11 October 2006" } ,
	{ "teamA":"Trinidad and Tobago","teamB":"Panama","matchDate":"18 March 2009","query":"Trinidad and Tobago vs Panama 18 March 2009" } ,
	{ "teamA":"Panama","teamB":"Trinidad and Tobago","matchDate":"07 September 2010","query":"Panama vs Trinidad and Tobago 07 September 2010" } ,
	{ "teamA":"Venezuela","teamB":"Panama","matchDate":"03 March 2010","query":"Venezuela vs Panama 03 March 2010" } ,
	{ "teamA":"Panama","teamB":"Venezuela","matchDate":"11 August 2010","query":"Panama vs Venezuela 11 August 2010" } ,
	{ "teamA":"China PR","teamB":"Paraguay","matchDate":"07 September 2010","query":"China PR vs Paraguay 07 September 2010" } ,
	{ "teamA":"Paraguay","teamB":"Costa Rica","matchDate":"11 August 2010","query":"Paraguay vs Costa Rica 11 August 2010" } ,
	{ "teamA":"Hong Kong","teamB":"Paraguay","matchDate":"17 November 2010","query":"Hong Kong vs Paraguay 17 November 2010" } ,
	{ "teamA":"Ivory Coast","teamB":"Paraguay","matchDate":"22 May 2008","query":"Ivory Coast vs Paraguay 22 May 2008" } ,
	{ "teamA":"Korea Republic","teamB":"Paraguay","matchDate":"12 August 2009","query":"Korea Republic vs Paraguay 12 August 2009" } ,
	{ "teamA":"New Zealand","teamB":"Paraguay","matchDate":"12 October 2010","query":"New Zealand vs Paraguay 12 October 2010" } ,
	{ "teamA":"Peru","teamB":"Paraguay","matchDate":"11 February 2009","query":"Peru vs Paraguay 11 February 2009" } ,
	{ "teamA":"Paraguay","teamB":"Peru","matchDate":"16 October 2012","query":"Paraguay vs Peru 16 October 2012" } ,
	{ "teamA":"Saudi Arabia","teamB":"Paraguay","matchDate":"20 August 2008","query":"Saudi Arabia vs Paraguay 20 August 2008" } ,
	{ "teamA":"Paraguay","teamB":"South Africa","matchDate":"17 September 2002","query":"Paraguay vs South Africa 17 September 2002" } ,
	{ "teamA":"South Africa","teamB":"Paraguay","matchDate":"26 March 2008","query":"South Africa vs Paraguay 26 March 2008" } ,
	{ "teamA":"Paraguay","teamB":"Venezuela","matchDate":"11 September 2012","query":"Paraguay vs Venezuela 11 September 2012" } ,
	{ "teamA":"Peru","teamB":"Costa Rica","matchDate":"26 March 2008","query":"Peru vs Costa Rica 26 March 2008" } ,
	{ "teamA":"Peru","teamB":"Costa Rica","matchDate":"27 March 2008","query":"Peru vs Costa Rica 27 March 2008" } ,
	{ "teamA":"Peru","teamB":"Costa Rica","matchDate":"08 October 2010","query":"Peru vs Costa Rica 08 October 2010" } ,
	{ "teamA":"Costa Rica","teamB":"Peru","matchDate":"15 August 2012","query":"Costa Rica vs Peru 15 August 2012" } ,
	{ "teamA":"El Salvador","teamB":"Peru","matchDate":"06 February 2009","query":"El Salvador vs Peru 06 February 2009" } ,
	{ "teamA":"Tunisia","teamB":"Peru","matchDate":"29 February 2012","query":"Tunisia vs Peru 29 February 2012" } ,
	{ "teamA":"Peru","teamB":"Uruguay","matchDate":"06 September 2013","query":"Peru vs Uruguay 06 September 2013" } ,
	{ "teamA":"USA","teamB":"Peru","matchDate":"04 September 2015","query":"USA vs Peru 04 September 2015" } ,
	{ "teamA":"Peru","teamB":"Venezuela","matchDate":"07 September 2012","query":"Peru vs Venezuela 07 September 2012" } ,
	{ "teamA":"Peru","teamB":"Venezuela","matchDate":"31 March 2015","query":"Peru vs Venezuela 31 March 2015" } ,
	{ "teamA":"Switzerland","teamB":"Romania","matchDate":"30 May 2012","query":"Switzerland vs Romania 30 May 2012" } ,
	{ "teamA":"Korea Republic","teamB":"Serbia","matchDate":"03 June 2011","query":"Korea Republic vs Serbia 03 June 2011" } ,
	{ "teamA":"Spain","teamB":"China PR","matchDate":"03 June 2012","query":"Spain vs China PR 03 June 2012" } ,
	{ "teamA":"China PR","teamB":"Tunisia","matchDate":"31 March 2015","query":"China PR vs Tunisia 31 March 2015" } ,
	{ "teamA":"Ivory Coast","teamB":"Tunisia","matchDate":"26 March 2008","query":"Ivory Coast vs Tunisia 26 March 2008" } ,
	{ "teamA":"Tunisia","teamB":"Ivory Coast","matchDate":"13 January 2012","query":"Tunisia vs Ivory Coast 13 January 2012" } ,
	{ "teamA":"Ivory Coast","teamB":"Tunisia","matchDate":"26 January 2013","query":"Ivory Coast vs Tunisia 26 January 2013" } ,
	{ "teamA":"Korea Republic","teamB":"Tunisia","matchDate":"28 May 2014","query":"Korea Republic vs Tunisia 28 May 2014" } ,
	{ "teamA":"Tunisia","teamB":"Saudi Arabia","matchDate":"14 October 2009","query":"Tunisia vs Saudi Arabia 14 October 2009" } ,
	{ "teamA":"Zambia","teamB":"Tunisia","matchDate":"13 January 2010","query":"Zambia vs Tunisia 13 January 2010" } ,
	{ "teamA":"Turkey","teamB":"France","matchDate":"03 April 1955","query":"Turkey vs France 03 April 1955" } ,
	{ "teamA":"Venezuela","teamB":"Uruguay","matchDate":"11 June 2013","query":"Venezuela vs Uruguay 11 June 2013" } ,
	{ "teamA":"China PR","teamB":"Uzbekistan","matchDate":"16 January 2011","query":"China PR vs Uzbekistan 16 January 2011" } ,
	{ "teamA":"China PR","teamB":"Uzbekistan","matchDate":"05 June 2011","query":"China PR vs Uzbekistan 05 June 2011" } ,
	{ "teamA":"China PR","teamB":"Uzbekistan","matchDate":"06 June 2013","query":"China PR vs Uzbekistan 06 June 2013" } ,
	{ "teamA":"Hong Kong","teamB":"Uzbekistan","matchDate":"19 November 2013","query":"Hong Kong vs Uzbekistan 19 November 2013" } ,
	{ "teamA":"Korea DPR","teamB":"Uzbekistan","matchDate":"24 December 2007","query":"Korea DPR vs Uzbekistan 24 December 2007" } ,
	{ "teamA":"Uzbekistan","teamB":"Korea DPR","matchDate":"29 August 2008","query":"Uzbekistan vs Korea DPR 29 August 2008" } ,
	{ "teamA":"Korea DPR","teamB":"Uzbekistan","matchDate":"11 October 2011","query":"Korea DPR vs Uzbekistan 11 October 2011" } ,
	{ "teamA":"Uzbekistan","teamB":"Korea DPR","matchDate":"11 November 2011","query":"Uzbekistan vs Korea DPR 11 November 2011" } ,
	{ "teamA":"Korea Republic","teamB":"Uzbekistan","matchDate":"05 July 2007","query":"Korea Republic vs Uzbekistan 05 July 2007" } ,
	{ "teamA":"Korea Republic","teamB":"Uzbekistan","matchDate":"11 October 2008","query":"Korea Republic vs Uzbekistan 11 October 2008" } ,
	{ "teamA":"Korea Republic","teamB":"Uzbekistan","matchDate":"28 January 2011","query":"Korea Republic vs Uzbekistan 28 January 2011" } ,
	{ "teamA":"Uzbekistan","teamB":"Korea Republic","matchDate":"11 September 2012","query":"Uzbekistan vs Korea Republic 11 September 2012" } ,
	{ "teamA":"Korea Republic","teamB":"Uzbekistan","matchDate":"11 June 2013","query":"Korea Republic vs Uzbekistan 11 June 2013" } ,
	{ "teamA":"Korea Republic","teamB":"Uzbekistan","matchDate":"22 January 2015","query":"Korea Republic vs Uzbekistan 22 January 2015" } ,
	{ "teamA":"Uzbekistan","teamB":"New Zealand","matchDate":"08 September 2014","query":"Uzbekistan vs New Zealand 08 September 2014" } ,
	{ "teamA":"Saudi Arabia","teamB":"Uzbekistan","matchDate":"09 October 2010","query":"Saudi Arabia vs Uzbekistan 09 October 2010" } ,
	{ "teamA":"United Arab Emirates","teamB":"Uzbekistan","matchDate":"28 January 2009","query":"United Arab Emirates vs Uzbekistan 28 January 2009" } ,
	{ "teamA":"Uzbekistan","teamB":"United Arab Emirates","matchDate":"03 March 2010","query":"Uzbekistan vs United Arab Emirates 03 March 2010" } ,
	{ "teamA":"United Arab Emirates","teamB":"Uzbekistan","matchDate":"29 January 2012","query":"United Arab Emirates vs Uzbekistan 29 January 2012" } ,
	{ "teamA":"United Arab Emirates","teamB":"Uzbekistan","matchDate":"12 October 2012","query":"United Arab Emirates vs Uzbekistan 12 October 2012" } ,
	{ "teamA":"United Arab Emirates","teamB":"Uzbekistan","matchDate":"22 March 2013","query":"United Arab Emirates vs Uzbekistan 22 March 2013" } ,
	{ "teamA":"Uzbekistan","teamB":"United Arab Emirates","matchDate":"05 March 2014","query":"Uzbekistan vs United Arab Emirates 05 March 2014" } ,
	{ "teamA":"Venezuela","teamB":"Costa Rica","matchDate":"13 May 2009","query":"Venezuela vs Costa Rica 13 May 2009" } ,
	{ "teamA":"Costa Rica","teamB":"Venezuela","matchDate":"27 June 2009","query":"Costa Rica vs Venezuela 27 June 2009" } ,
	{ "teamA":"Venezuela","teamB":"Costa Rica","matchDate":"09 February 2011","query":"Venezuela vs Costa Rica 09 February 2011" } ,
	{ "teamA":"Venezuela","teamB":"Costa Rica","matchDate":"22 December 2011","query":"Venezuela vs Costa Rica 22 December 2011" } ,
	{ "teamA":"Venezuela","teamB":"El Salvador","matchDate":"23 March 2008","query":"Venezuela vs El Salvador 23 March 2008" } ,
	{ "teamA":"El Salvador","teamB":"Venezuela","matchDate":"07 August 2011","query":"El Salvador vs Venezuela 07 August 2011" } ,
	{ "teamA":"Venezuela","teamB":"Korea DPR","matchDate":"06 March 2010","query":"Venezuela vs Korea DPR 06 March 2010" } ,
	{ "teamA":"Zambia","teamB":"Ivory Coast","matchDate":"12 February 2012","query":"Zambia vs Ivory Coast 12 February 2012" } ,
	{ "teamA":"Zambia","teamB":"Korea DPR","matchDate":"21 November 2009","query":"Zambia vs Korea DPR 21 November 2009" } ,
	{ "teamA":"Zambia","teamB":"Korea Republic","matchDate":"09 January 2010","query":"Zambia vs Korea Republic 09 January 2010" } ,
	{ "teamA":"Korea Republic","teamB":"Zambia","matchDate":"15 August 2012","query":"Korea Republic vs Zambia 15 August 2012" } ,
	{ "teamA":"Zambia","teamB":"Saudi Arabia","matchDate":"08 September 1999","query":"Zambia vs Saudi Arabia 08 September 1999" } ,
	{ "teamA":"Zambia","teamB":"South Africa","matchDate":"07 October 2006","query":"Zambia vs South Africa 07 October 2006" } ,
	{ "teamA":"South Africa","teamB":"Zambia","matchDate":"27 July 2008","query":"South Africa vs Zambia 27 July 2008" } ,
	{ "teamA":"South Africa","teamB":"Zambia","matchDate":"27 January 2009","query":"South Africa vs Zambia 27 January 2009" } ,
	{ "teamA":"South Africa","teamB":"Zambia","matchDate":"14 November 2012","query":"South Africa vs Zambia 14 November 2012" } ,
	{ "teamA":"South Africa","teamB":"Zambia","matchDate":"17 July 2013","query":"South Africa vs Zambia 17 July 2013" } ,

]






print('"teamA","teamB","matchDate","venue"')
for match in match_data:
	URL_PARAMS['q'] = match['query']
	query_data = urlencode(URL_PARAMS)
	result  = request(SEARCH_URL + query_data)
	tree = html.fromstring(result)
	xpath = "//*[contains(concat(' ', normalize-space(@class), ' '), ' has-score-detail ')]/a"
	links = tree.xpath(xpath)
	venue = ""
	if(links and len(links) > 0):
		match_url = ROOT_URL + links[0].attrib['href']
		result  = request(match_url)
		m_regex = re.search("Stadium: (.*)</li>",result)
		if m_regex:
			venue = m_regex.group(1)

	print('"'+match['teamA']+'","'+match['teamB']+'","'+match['matchDate']+'","'+venue+'"')



